<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Save for audit</name>
   <tag></tag>
   <elementGuidId>f361371d-ff5c-40c1-b892-e9cc130f0144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='checkBox_lab'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Save for audit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7f4615d-2780-49b7-a14a-17c5a5608c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-h300 check-font</value>
      <webElementGuid>5087b168-d6ed-4c5d-a80a-95187413e5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBox_lab</value>
      <webElementGuid>86ab8e67-ffbb-4297-8bc3-d908bea50d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save for audit </value>
      <webElementGuid>052b5f9c-4d90-4b68-ac9d-5183f60e5bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-6974-14&quot;)/div[@class=&quot;row&quot;]/form[@class=&quot;el-form el-form--default el-form--label-right&quot;]/div[@class=&quot;row col-9 mb-3&quot;]/div[@class=&quot;col-lg-5 mb-2&quot;]/label[@class=&quot;el-checkbox&quot;]/span[@class=&quot;el-checkbox__label&quot;]/div[@id=&quot;checkBox_lab&quot;]</value>
      <webElementGuid>81c7e74d-4b9a-43fa-9b07-add1a38aa948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='checkBox_lab'])[2]</value>
      <webElementGuid>d06538ff-8b69-4de4-8942-da022c544f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-id-6974-14']/div/form/div/div[3]/label[2]/span[2]/div</value>
      <webElementGuid>090bed13-af52-4020-8cd5-1e56222300c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save for future use'])[1]/following::div[1]</value>
      <webElementGuid>d1751704-badf-455a-a052-598103733e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[1]/preceding::div[1]</value>
      <webElementGuid>71cb5a3d-68a7-45aa-b58b-629b85875f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save for audit']/parent::*</value>
      <webElementGuid>ca0fd3b8-7460-4d68-9846-f8c2c87275dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]/div</value>
      <webElementGuid>1344c1a8-d3f7-4d23-9a5a-cab5ed515738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkBox_lab' and (text() = 'Save for audit ' or . = 'Save for audit ')]</value>
      <webElementGuid>7277d300-d503-487c-91bc-f0adcd56ed76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
