<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_offline_operator</name>
   <tag></tag>
   <elementGuidId>91e750fd-0b11-4d1d-b2f1-0235e0fa2ceb</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='operator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#operator</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'assets/img/dots-three-outline-vertical.10d331c2.svg' and @id = 'operator']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;res-2a91447 123.3.3.3 Saas 1 &lt;null> YES offline&quot;i] >> #operator</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce961926-bfba-4a1b-9fff-012487f2896f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/dots-three-outline-vertical.10d331c2.svg</value>
      <webElementGuid>e3bc9496-ac91-4c65-bfb9-55ff2e0ef22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img el-tooltip__trigger el-tooltip__trigger</value>
      <webElementGuid>fe431024-772a-46cf-bb88-e5cbebfe38a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operator</value>
      <webElementGuid>1600364b-92d0-409e-82a5-de4e15488c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c108e062-c2be-4ede-bb82-3061f4b7d5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41fb3bbf-647e-4988-9114-7955d00b326e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>el-id-9792-72</value>
      <webElementGuid>d7565dfe-61ad-419a-9117-38615d1c629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>009acba5-8755-4919-8e84-feb370c06a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>5b35643a-82b4-4dd3-a730-d0ee2e30b71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resource-table&quot;)/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_8_column_59 is-right el-table__cell&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;el-dropdown&quot;]/img[@id=&quot;operator&quot;]</value>
      <webElementGuid>66c9bf12-c301-4aaa-8694-7082c99242e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='operator']</value>
      <webElementGuid>31d5044a-6a8f-4092-9a89-1d95cc46fab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resource-table']/div/div[3]/div/div/div/table/tbody/tr/td[9]/div/div/img</value>
      <webElementGuid>1f7a1e5c-84b4-41c0-a188-eac6c4416b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/img</value>
      <webElementGuid>af8556b1-b94c-45f5-b0a8-96b758e4ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/img/dots-three-outline-vertical.10d331c2.svg' and @id = 'operator']</value>
      <webElementGuid>f8ad73d7-0642-4624-964b-e1db128f58d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
