<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>9265a017-edff-448c-99e0-a6861463cbf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.page-center.ztn-page-t400 > a.a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSignin']/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;现在创建一个。&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33bb4c47-80f4-4445-acba-ee9330da780e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3896978-51c5-40a8-8451-d9f6ab50a3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/idp/stronggate/signup</value>
      <webElementGuid>5162a197-f7ab-4a9b-8ae1-f41e8a820599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>现在创建一个。</value>
      <webElementGuid>8ca46bdb-eebc-43b6-94d2-c97c217e8053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignin&quot;)/div[@class=&quot;page-center ztn-page-t400&quot;]/a[@class=&quot;a&quot;]</value>
      <webElementGuid>62afdbc3-fc51-4f7f-929a-aed7e0cf1402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignin']/div[5]/a</value>
      <webElementGuid>28acd72b-c1ed-423a-bc46-169f0e1d16f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'现在创建一个。')]</value>
      <webElementGuid>cd414a81-3a41-4fb9-96de-574cdb559045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='还没有StrongGate ID？'])[1]/following::a[1]</value>
      <webElementGuid>45fe567c-f567-4231-836a-5ebf5226f7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登录'])[2]/following::a[1]</value>
      <webElementGuid>29c153f0-35c8-496c-b736-dd687a275e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条款'])[1]/preceding::a[1]</value>
      <webElementGuid>9ba964bb-fd96-4daf-afe0-bbfdd732d4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='现在创建一个。']/parent::*</value>
      <webElementGuid>385e37ca-7a2a-4be8-a8ca-d7ffb222ff54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/idp/stronggate/signup')]</value>
      <webElementGuid>23e4744d-9572-4047-a7e2-d838d3e8893a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>e849fdf5-f022-40b6-b0bf-e9a082e7b0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/idp/stronggate/signup' and (text() = '现在创建一个。' or . = '现在创建一个。')]</value>
      <webElementGuid>7ae351b0-c262-485b-ada7-b1a195098420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
