<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StrongGate</name>
   <tag></tag>
   <elementGuidId>ef2cb8b2-69af-4bef-9f38-9ccd5697b03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='identity']/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;使用StrongGate登录&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3e26d6d-8653-4db6-9b6b-dbbf598c0835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t600</value>
      <webElementGuid>6fd7569d-ee44-4449-bcb8-de7edd1302be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>使用StrongGate登录</value>
      <webElementGuid>ea08a14d-22d5-47f3-910c-454c0fe489ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identity&quot;)/button[@class=&quot;button-idp&quot;]/div[@class=&quot;ztn-page-t600&quot;]</value>
      <webElementGuid>a3248a66-01cd-42cb-ae03-c6bcb3e674b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identity']/button/div</value>
      <webElementGuid>f25bd42b-6b6f-478d-9cb2-b47a61214d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StrongGate商业版试用30天，无需信用卡。StrongGate基础版永远免费。'])[1]/following::div[2]</value>
      <webElementGuid>eb18edef-f141-43d7-b08a-8e1b165dab34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='免费注册StrongGate'])[1]/following::div[3]</value>
      <webElementGuid>4807a49f-23e2-4fdf-bca3-ee380d45c200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用Microsoft登录'])[1]/preceding::div[1]</value>
      <webElementGuid>51d6dd25-7362-4c82-b115-22e9e0e27d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用GitHub登录'])[1]/preceding::div[2]</value>
      <webElementGuid>02ee82c2-8983-456c-b6b4-04821167f6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='使用StrongGate登录']/parent::*</value>
      <webElementGuid>ae61bdad-1abb-4823-b2a8-92d90bbb07bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>a5a2e90f-2541-4d31-a975-d8784ef99dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '使用StrongGate登录' or . = '使用StrongGate登录')]</value>
      <webElementGuid>9e03e690-1605-4949-83eb-291c3a2f5445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
