<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StrongGate</name>
   <tag></tag>
   <elementGuidId>fa4012e1-852f-4cb6-84db-35d71216e734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='identity']/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;使用StrongGate登录&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46f77bdb-d6eb-40c1-bc2f-e9bf701b8b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t600</value>
      <webElementGuid>9a5993b9-e65e-44ef-a56c-1faf80cb53a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>使用StrongGate登录</value>
      <webElementGuid>15ed73b9-5bac-4b05-83bf-da934c0f9431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identity&quot;)/button[@class=&quot;button-idp&quot;]/div[@class=&quot;ztn-page-t600&quot;]</value>
      <webElementGuid>ee982f8d-7cf8-4c71-a3f1-09eb856fb5b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identity']/button/div</value>
      <webElementGuid>b6d5cee1-8b76-41de-8e03-50142ad5f26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test333'])[3]/following::div[2]</value>
      <webElementGuid>eabe24a8-90f1-47fd-b4c6-0990fe51c66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用Microsoft登录'])[1]/preceding::div[1]</value>
      <webElementGuid>73547d23-0ef8-473f-8c1e-9e271f13f0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用GitHub登录'])[1]/preceding::div[2]</value>
      <webElementGuid>aad331b9-bb3e-46e4-a998-6f1458f6ad79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='使用StrongGate登录']/parent::*</value>
      <webElementGuid>a4ae9c85-554c-422c-8249-a1a7ee8df8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>1046a381-4354-4d8c-a1f2-5f47eda0d462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '使用StrongGate登录' or . = '使用StrongGate登录')]</value>
      <webElementGuid>77340945-8e75-4abc-9d7b-774fecb8ae24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
