<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Split Tunnel_locationSplitTunnelList</name>
   <tag></tag>
   <elementGuidId>13fcc066-0283-4147-a496-2b5a0c6b7afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationSplitTunnelList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='locationSplitTunnelList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#locationSplitTunnelList</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>060a5648-d44c-4714-a8a5-a0d407e3305a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tagDiv</value>
      <webElementGuid>65575423-f3ec-4d77-90c2-313f19bc0d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationSplitTunnelList</value>
      <webElementGuid>77f679c4-71f8-485e-93b7-66a047e376b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationSplitTunnelList&quot;)</value>
      <webElementGuid>da834e31-7fdf-4939-8aa0-a33887a88974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='locationSplitTunnelList']</value>
      <webElementGuid>3d94e4b9-15e5-4c95-9f98-0b9115a69ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/form/div[3]/div/div[3]/table/tr[2]/td[3]/div</value>
      <webElementGuid>8bbd338a-5a25-4496-85ac-fa12f09d3a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Split Tunnel'])[1]/following::div[2]</value>
      <webElementGuid>5f2e8fae-12cb-446b-9a71-f4b8e66fde84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Ranges'])[1]/following::div[11]</value>
      <webElementGuid>d0bbde91-95e4-404e-b3e1-460f3a795025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[2]</value>
      <webElementGuid>a3cb4420-cd07-4453-aab2-d62e9237a95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Location'])[1]/preceding::div[2]</value>
      <webElementGuid>a135fe78-c2c4-49a2-b3a5-27bb6226e6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div</value>
      <webElementGuid>68362916-c96d-4dbb-967c-64623ea77646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'locationSplitTunnelList']</value>
      <webElementGuid>fa456d4f-b816-4c4f-a86f-64edddf8e250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
