<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2c02c963-7c0f-4f9a-9329-c33d97a19ff4</name>
   <tag></tag>
   <elementGuidId>856317ec-980a-4e78-a974-f7d6cb60a538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.el-table_7_column_41.el-table__cell > div.cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-id-3690-43']/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2c02c963-7c0f-4f9a-9329-c33d97a19ff4&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c54127e-fb6c-4f45-9da8-b3c8db15fec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>d0363154-f36a-445b-9a6b-2fdff6c983f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2c02c963-7c0f-4f9a-9329-c33d97a19ff4</value>
      <webElementGuid>1621d05a-5f4a-4f17-a7e2-c2a6b5bb4a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-3690-43&quot;)/div[@class=&quot;el-table--fit el-table--fluid-height el-table--enable-row-hover el-table--enable-row-transition el-table el-table--layout-fixed ztn-common-table mb-3 is-scrolling-none&quot;]/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_7_column_41 el-table__cell&quot;]/div[@class=&quot;cell&quot;]</value>
      <webElementGuid>7e6f337e-2fbd-43a3-9e40-7d65c64fab06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-id-3690-43']/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[3]/div</value>
      <webElementGuid>66ef44b5-e1c1-4995-8101-c4e5dfb4ab1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anywhere'])[1]/following::div[2]</value>
      <webElementGuid>f422d394-ad5b-4d4d-bed3-16bc14bd8bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items: 1-0'])[2]/preceding::div[9]</value>
      <webElementGuid>686ed756-9c07-413b-94c9-d2676e082614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2c02c963-7c0f-4f9a-9329-c33d97a19ff4']/parent::*</value>
      <webElementGuid>915a7f0b-2170-47b8-9624-32b8ec19abab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[3]/div</value>
      <webElementGuid>3eb53fd1-e8b4-4c7c-a11e-31f6c9b63292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2c02c963-7c0f-4f9a-9329-c33d97a19ff4' or . = '2c02c963-7c0f-4f9a-9329-c33d97a19ff4')]</value>
      <webElementGuid>07c44e1c-02eb-4472-9e37-1999f4790d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
