<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_----  ----_autorenew</name>
   <tag></tag>
   <elementGuidId>da6d6432-12aa-49e7-9fa6-2d508078e9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autorenew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='autorenew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#autorenew</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62bd1be6-1bd4-492a-9c5d-a6f58f89b06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/autorenew.8d5cb772.svg</value>
      <webElementGuid>68a9f534-d8f2-4761-9ee0-c0c60187aab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autorenew</value>
      <webElementGuid>e5847d95-1ca5-451b-bef5-40a5a1d9483c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autorenew&quot;)</value>
      <webElementGuid>0275620b-8da2-4f3f-abd4-de8aeedacd95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='autorenew']</value>
      <webElementGuid>685208ef-65ef-479a-9c2d-fddae3958c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/form/div[2]/div/div[6]/div/div/div[3]/img</value>
      <webElementGuid>3782595a-8d2a-4c8d-b1e2-32b4fac632ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>41ebce28-f84f-49bb-b893-26f9a57fb88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/img/autorenew.8d5cb772.svg' and @id = 'autorenew']</value>
      <webElementGuid>46a64575-75da-4507-b216-38b0ddf6a947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
