<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IP Ranges_locationIpRangeList</name>
   <tag></tag>
   <elementGuidId>1125abb2-a268-4593-9714-20379ba1b2dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationIpRangeList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locationIpRangeList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;IP Ranges These IP Ranges can be used by the Access Rules of Network Access Policy to control whether a user device can access these IP Ranges. e.g. 10.0.0.1/16, 172.16.0.0-172.16.0.233&quot;i] >> internal:attr=[placeholder=&quot;e.g. 10.0.0.1/16,   172.16.0.0-172.16.0.233&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f58b285a-e514-4d3e-a8f8-5e9d51965d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 10.0.0.1/16,   172.16.0.0-172.16.0.233</value>
      <webElementGuid>ce6c8259-43ba-4802-a610-fee85f0419df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c56c413f-6610-402e-9742-c82c64ec97be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationIpRangeList</value>
      <webElementGuid>ee007bdd-bc23-4b05-9b03-83e71829af1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationIpRangeList&quot;)</value>
      <webElementGuid>fab609cb-ba92-4267-945c-468862c7e61a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locationIpRangeList']</value>
      <webElementGuid>dcdd8eaf-ab6f-4d11-8c4d-487e67920bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/form/div[3]/div/div[3]/table/tr/td[3]/div/input</value>
      <webElementGuid>d256991a-c1eb-468c-8d41-e8202070b5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>86ae04e4-2913-4ab6-b199-344bd185eb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g. 10.0.0.1/16,   172.16.0.0-172.16.0.233' and @id = 'locationIpRangeList']</value>
      <webElementGuid>b771911d-6957-4a05-8d4e-ebe3a63cf626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
