<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nearest Public IP_locationNearestPublicIp</name>
   <tag></tag>
   <elementGuidId>ddfd4f03-ecb5-487e-aee1-0797c596a128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationNearestPublicIp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locationNearestPublicIp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;input one or more public IP here e.g. 19.131.66.13&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca6b3b5b-af45-47ad-ba3f-1fa7ef82f357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>input one or more public IP here e.g. 19.131.66.13</value>
      <webElementGuid>5cfd5402-2ced-4b33-9e21-17e0911ddfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77b5620d-a567-4e54-8560-70299ff9f5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationNearestPublicIp</value>
      <webElementGuid>8b3a492f-0089-4160-b5a1-be21bf3d4656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationNearestPublicIp&quot;)</value>
      <webElementGuid>5c2dc918-bf9c-4192-915c-3a6273428aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locationNearestPublicIp']</value>
      <webElementGuid>3fb91f5f-e6ad-4888-8e19-7ea265c4f43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/form/div[2]/div/div[5]/div/div/div/input</value>
      <webElementGuid>0caf8c57-148d-44de-b7ad-79015fa25d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>d5e5b5eb-fcc2-425a-a1d1-2f061b5413a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'input one or more public IP here e.g. 19.131.66.13' and @id = 'locationNearestPublicIp']</value>
      <webElementGuid>a6f8f50f-6c2f-4f17-bf18-b4a9c6acfc11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
