<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Device exists within these IP Ranges_input</name>
   <tag></tag>
   <elementGuidId>00c7a12c-7069-46ae-8d72-a9c82da09af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/form/div/div[3]/div[2]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tagDiv > input.input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tag edit field&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32c1da67-c599-4496-befc-79726dbdb72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tag edit field</value>
      <webElementGuid>6cdcbf9c-ecd6-439b-a49a-11b91b89af73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee51922a-93df-4178-a0ac-a81d0938ec85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;el-form el-form--default el-form--label-top&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 layer_board mb-4&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;tagDiv&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>34b98095-b49c-427e-bad8-7a83f2e44aaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/form/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>dc7faf62-9ac5-4a72-82fc-8b024060e16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>00a022d7-ab04-4093-aee3-35c9c4d4e5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tag edit field']</value>
      <webElementGuid>bdd5b533-6976-4040-90cf-f1de360750f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>1e61a491-30ab-476d-bc13-31fa79ee24ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>31560608-494d-4d93-a6d0-fe576f423099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[3]/div/div/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>52dc153e-cd54-4218-962e-e7797fbf18ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>f3f5f786-79b7-4ce1-aed3-6ea8e1c811df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locationIpAddress']/input</value>
      <webElementGuid>13d90ced-2b4f-414e-9265-5c28967ed800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>adc85ced-796f-4587-a413-ff380c4dcc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g. 10.0.0.1/16,172.16.0.0-172.16.0.233']</value>
      <webElementGuid>a9e98f35-f3e0-433c-9542-5e61483a9406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
