<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nearest Public IP_input</name>
   <tag></tag>
   <elementGuidId>bc667b05-a514-4a19-b97d-c46d6b6a0efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationNearestPublicIp > input.input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='locationNearestPublicIp']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;input one or more public IP here e.g. 19.131.66.13&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a844bfc8-449c-4dbf-8eec-48991d6eb8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>input one or more public IP here e.g. 19.131.66.13</value>
      <webElementGuid>650c8283-398d-4955-ade8-6431c6bbae0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8453f2a-5d89-4b5a-b694-e88152969aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationNearestPublicIp&quot;)/input[@class=&quot;input&quot;]</value>
      <webElementGuid>2d905eaa-eefa-42a4-90fa-1131e92f5133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locationNearestPublicIp']/input</value>
      <webElementGuid>6067a0c8-8307-4a4f-8c8b-7091a6b14bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>d794d56d-1105-47ab-82bb-abc959a37e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'input one or more public IP here e.g. 19.131.66.13']</value>
      <webElementGuid>6fae168d-a04b-44c6-8bcd-62fb25ecb499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locationSplitTunnelList']/input</value>
      <webElementGuid>7a058e9d-8c26-4c03-a9a1-d76f3dab199e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>971ebb60-0293-4129-a07c-313600f1d927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
