<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Device exists within these IP Ranges__bd2461</name>
   <tag></tag>
   <elementGuidId>b361090b-2bc1-493f-bcca-64cde670825f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationIpAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locationIpAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g. 10.0.0.1/16,172.16.0.0-172.16.0.233&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0531bd84-fc8f-47be-9b40-215e1ab32f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 10.0.0.1/16,172.16.0.0-172.16.0.233</value>
      <webElementGuid>3e3b05ad-edf9-4abc-97d6-d307cc670881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99d94870-02cb-4787-b2fe-22841f6efec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationIpAddress</value>
      <webElementGuid>fbe0b311-4823-4d63-984b-92bd93093141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationIpAddress&quot;)</value>
      <webElementGuid>22fca309-fc56-427e-a6da-1e1ae024bf84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locationIpAddress']</value>
      <webElementGuid>8f41e018-1a57-4fda-8a1f-53522efbdc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/form/div[2]/div/div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>c1503a24-271e-444c-aef4-5b313f282baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>93a0ece9-31a4-4197-b9df-b6781b637ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g. 10.0.0.1/16,172.16.0.0-172.16.0.233' and @id = 'locationIpAddress']</value>
      <webElementGuid>c5ffa09a-5310-466d-836a-148d7432816f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
