<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Split Tunnel_locationSplitTunnelList</name>
   <tag></tag>
   <elementGuidId>1f6700e9-371d-4222-b2b1-f4a822116504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationSplitTunnelList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locationSplitTunnelList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;e.g. 10.0.0.1/16, 172.16.0.0-172.16.0.233&quot;s] >> internal:attr=[placeholder=&quot;e.g. 10.0.0.1/16,   172.16.0.0-172.16.0.233&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08a3b1a8-c31a-43f6-bde9-9937060c215e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 10.0.0.1/16,   172.16.0.0-172.16.0.233</value>
      <webElementGuid>12032aea-80e3-4c83-9e3c-268c6888fef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>604ac7ed-ad17-4904-be12-76a246cab673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationSplitTunnelList</value>
      <webElementGuid>27848323-bb3e-41be-8f6a-7c3cd35598ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationSplitTunnelList&quot;)</value>
      <webElementGuid>d9256c75-ca00-4be3-9dea-1db613cceb0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locationSplitTunnelList']</value>
      <webElementGuid>ab25003c-ec49-49b9-af2a-2521a80bc1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/form/div[3]/div/div[3]/table/tr[2]/td[3]/div/input</value>
      <webElementGuid>2e5094b1-c6d3-4007-b551-7a8caf58878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/input</value>
      <webElementGuid>0330bbe1-da45-41b7-8e43-8f439b9d3d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g. 10.0.0.1/16,   172.16.0.0-172.16.0.233' and @id = 'locationSplitTunnelList']</value>
      <webElementGuid>45ce6f66-0887-4d42-a64a-9d738a76240e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
