<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_u-001</name>
   <tag></tag>
   <elementGuidId>a58a257a-7244-4c6a-aeb0-b16cace978d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationTokenServersOption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='locationTokenServersOption']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;u-001&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7b526bed-d569-4abf-845b-c86199591cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationTokenServersOption</value>
      <webElementGuid>fdb2200c-86de-447a-8a5d-2c9e4a861b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item hover</value>
      <webElementGuid>22f50cc9-64c5-47f6-bad9-7d02ea2343f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>75d8ab6c-0baa-478e-92ab-1d680e653412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6eac836d-305e-4b5a-8087-ea58db4601ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>u-001</value>
      <webElementGuid>705547a4-bb72-485d-a393-fe406c6ccf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationTokenServersOption&quot;)</value>
      <webElementGuid>247d5efc-63b0-44a8-ab3e-d0dd8107e057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='locationTokenServersOption']</value>
      <webElementGuid>c7e3dd68-eb7e-4f30-bfe5-c4aeb3559d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='el-id-3690-169']/li</value>
      <webElementGuid>768b0eef-e8ac-4386-a485-e01f6d53765b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='im-002'])[1]/following::li[1]</value>
      <webElementGuid>fda4423f-c4a4-4be2-866f-bc2cf8330de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='im-001'])[1]/following::li[2]</value>
      <webElementGuid>5c9f8713-83df-4a71-b293-38c8acbcc36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='u-001'])[2]/preceding::li[1]</value>
      <webElementGuid>8718c812-34f5-47cb-be3d-47c72c7a82d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/ul/li</value>
      <webElementGuid>24c066a6-6367-4696-9954-80cb6caf8365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'locationTokenServersOption' and (text() = 'u-001' or . = 'u-001')]</value>
      <webElementGuid>b57bb231-a8fa-40b5-b7c1-17ce77cf65e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
