<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>f1f318e8-b717-48b8-876c-72d3dca9758d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectLocation > div.btn-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='selectLocation']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#selectLocation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0afb300e-69e7-4cb6-ba5a-380987c33954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-content</value>
      <webElementGuid>d0f90e8d-b591-43ca-84e5-8f57b8207e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select </value>
      <webElementGuid>2aa65dd3-24d9-4dff-9347-0ca8b7d43d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectLocation&quot;)/div[@class=&quot;btn-content&quot;]</value>
      <webElementGuid>7edaf5e3-045e-4142-b9a0-10f53757974b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='selectLocation']/div</value>
      <webElementGuid>daaec2ee-23fc-486c-98c3-cd26d58349ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>cedf3c66-40d3-42a7-b0b4-3d0e0d43cd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button/div</value>
      <webElementGuid>43c301ff-9c90-4707-910c-eda12bdd69ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Select ' or . = ' Select ')]</value>
      <webElementGuid>6ee3d13b-0467-4c0c-8aaa-2f7a544760ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
