<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comments_macAddress</name>
   <tag></tag>
   <elementGuidId>8f485642-d80c-4f84-a565-5b9bc45ec794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#macAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='macAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#macAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4911f3a0-405e-4e7a-98b7-e76f9080bb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>macAddress</value>
      <webElementGuid>8fa276d2-ba4b-4907-a6bb-41f90a298d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-detail</value>
      <webElementGuid>cbb411f6-b0f7-485c-8ba2-d13bd5d3a4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;macAddress&quot;)</value>
      <webElementGuid>59ffb748-3404-4518-bd5c-98caaffc6ee6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='macAddress']</value>
      <webElementGuid>be5e40bb-4d4d-4e01-92f1-ff55740ea98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>39a97263-299f-4106-80f3-b5ed98374b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>fc122ec5-49c0-4322-a4a8-ec33401dcebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'macAddress']</value>
      <webElementGuid>f0a20d17-3f4c-4bc2-95fa-b71a2578613f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
