<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comments_ipAddress</name>
   <tag></tag>
   <elementGuidId>891f7df0-544d-4e9d-885b-e3bbee6e1344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ipAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ipAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ipAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9db95bfa-3614-4425-8a29-410350ebee44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ipAddress</value>
      <webElementGuid>7f4f66eb-b2ee-497d-a000-13d2d8ad6b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-detail</value>
      <webElementGuid>a6d5d7af-ca21-4d14-bedb-199c9de3e4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ipAddress&quot;)</value>
      <webElementGuid>d962e5d4-3cce-4258-9488-b71fbced9aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ipAddress']</value>
      <webElementGuid>5a3d3587-16f5-4f00-8e06-4bb5980e84f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[3]/div/div/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>7623c3d1-a110-4617-8df4-ffeab67aee75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>61a0e334-ed0d-44ff-9dc7-619101ab20d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ipAddress']</value>
      <webElementGuid>db9d2df5-40f0-4463-962f-1f605f70dbb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
