<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>e3285e66-69c1-4457-826d-d1667a2d1b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t400</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;创建新身份帐户&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9507634f-da7c-431d-b0c9-efa20f6b5cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t400</value>
      <webElementGuid>6fbf72e1-c6a2-4ae8-8f5a-ee8483587012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>创建新身份帐户</value>
      <webElementGuid>fc13c32a-15a0-44f8-a471-9700eb31a725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button&quot;)/div[@class=&quot;ztn-page-t400&quot;]</value>
      <webElementGuid>7eb34715-7983-4ab0-ad76-3ec1b62531f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button']/div</value>
      <webElementGuid>c38a1458-6bee-434b-95ed-bc40d54d8ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='将向您的电子邮件地址发送一封带有一次性密码的电子邮件。'])[1]/following::div[2]</value>
      <webElementGuid>8d000854-af91-47d2-ba64-ccd9d298f12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='电子邮件地址作为您的登录ID：'])[1]/following::div[4]</value>
      <webElementGuid>7c35fe5b-7c93-418f-9da9-4acfd514617d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='创建帐户，即表示您同意'])[1]/preceding::div[1]</value>
      <webElementGuid>4b8fba5f-a17b-4bd4-b614-682803a7c281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='服务条款协议'])[1]/preceding::div[1]</value>
      <webElementGuid>ad64a98c-1eb7-4b47-9f4a-99f8f6e5ab3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='创建新身份帐户']/parent::*</value>
      <webElementGuid>5c7030dd-1e96-4fc7-b43f-c37251bb3c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>db7f0d9b-5b3c-45d1-b35a-cba990cd638e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '创建新身份帐户' or . = '创建新身份帐户')]</value>
      <webElementGuid>b17404bb-256a-4cc6-b59f-1cc257665520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
