<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__teamDomain</name>
   <tag></tag>
   <elementGuidId>eae89d17-7f16-4288-ab00-0bed27425a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-team-domain']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt-team-domain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;团队域：&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>629b9dde-fb97-49c3-9652-b0ba25e2780d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-team-domain</value>
      <webElementGuid>9875943c-967d-4b25-a003-b700442528fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teamDomain</value>
      <webElementGuid>6e7f5303-44d2-44ba-8b4e-61af4beee9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e672528d-4b4a-4b1b-a6a4-4c33ca46dfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>团队域：</value>
      <webElementGuid>39e49c65-dd50-4f66-9488-6928a48974a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>teamDomainFocus()</value>
      <webElementGuid>ad319ab1-5f9e-43e3-99f3-4a4a5e957b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>verification()</value>
      <webElementGuid>6fe2f95c-8a9b-4443-876c-64f20f352401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-team-domain&quot;)</value>
      <webElementGuid>2687aecb-6f0a-4523-b860-d9387a0537de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-team-domain']</value>
      <webElementGuid>51671887-ff24-46ce-b760-8af6a1e3f62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignUp']/div[6]/input</value>
      <webElementGuid>6c6ca5fd-b006-418e-91af-1342638d2d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>3f1928cc-1562-495b-a4cf-a4f5bcf962f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txt-team-domain' and @name = 'teamDomain' and @placeholder = '团队域：']</value>
      <webElementGuid>95917ed5-d1dc-45c8-9884-f5e78727c477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
