<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select and Confirm_el-input__suffix-inner</name>
   <tag></tag>
   <elementGuidId>5764e1b5-5eda-4beb-b87a-ace6be591da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-collapse-content-763']/div/div/table/tr[3]/td[2]/div/div/div[2]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.p-2 > div.el-select > div.select-trigger.el-tooltip__trigger.el-tooltip__trigger > div.el-input.el-input--suffix > div.el-input__wrapper > span.el-input__suffix > span.el-input__suffix-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > .p-2 > .el-select > .select-trigger > .el-input > .el-input__wrapper > .el-input__suffix > .el-input__suffix-inner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b10acdd-83ba-4d13-b20b-826dcac78cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__suffix-inner</value>
      <webElementGuid>aa43390a-39bf-444a-b46d-c4a97a4c3a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-collapse-content-763&quot;)/div[@class=&quot;el-collapse-item__content&quot;]/div[@class=&quot;card-body&quot;]/table[@class=&quot;mb-3&quot;]/tr[3]/td[@class=&quot;p-2&quot;]/div[@class=&quot;el-select&quot;]/div[@class=&quot;select-trigger el-tooltip__trigger el-tooltip__trigger&quot;]/div[@class=&quot;el-input el-input--suffix&quot;]/div[@class=&quot;el-input__wrapper&quot;]/span[@class=&quot;el-input__suffix&quot;]/span[@class=&quot;el-input__suffix-inner&quot;]</value>
      <webElementGuid>acdab710-04e6-4910-9d21-7e7d771f1e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-collapse-content-763']/div/div/table/tr[3]/td[2]/div/div/div[2]/div/span/span</value>
      <webElementGuid>b8d262bc-2f70-4b26-8fcc-70e85409c804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select and Confirm'])[1]/following::span[3]</value>
      <webElementGuid>377e3c5c-17fe-4dc6-ba4d-3bf4f6702d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='member support desc'])[1]/following::span[4]</value>
      <webElementGuid>ea06a5a5-3c20-455e-82e9-c02ea2e3197d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel'])[1]/preceding::span[3]</value>
      <webElementGuid>51d8bd8d-355c-4cd0-923b-9868ca2e8c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/div[2]/div/span/span</value>
      <webElementGuid>53476ed9-bc41-4ca5-adf5-201ad3b02285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
