<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add GEO Proxy Policy</name>
   <tag></tag>
   <elementGuidId>710703fb-8aac-47e4-a057-c7af934c4227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-policy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-policy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add GEO Proxy Policy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1140124-dc75-4c22-86f1-b34f128198d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>716293e1-2e81-4f7b-9354-1b6bd8bc44d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85abc993-bbd3-4cd9-99f5-e4d8459d621e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-policy</value>
      <webElementGuid>5b3a9e72-58c1-4a1c-b86e-ea7c8468aa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add GEO Proxy Policy </value>
      <webElementGuid>93b0853c-b04a-42be-91ab-a69d0e293967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-policy&quot;)</value>
      <webElementGuid>871752d3-645e-4d10-acc2-25855d3b310d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-policy']</value>
      <webElementGuid>6ccc64ff-e710-401b-a8fd-706391a14787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div[3]/button</value>
      <webElementGuid>6b9cebbe-fee2-46cb-83bc-409eebd4566b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/button</value>
      <webElementGuid>b763a186-5819-4665-8c96-65cb80628810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'add-policy' and (text() = 'Add GEO Proxy Policy ' or . = 'Add GEO Proxy Policy ')]</value>
      <webElementGuid>caf7c31e-b28f-4888-86ad-a3d719deebd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
