<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Geo-Proxy Server Preference is_policy-r_369fbe</name>
   <tag></tag>
   <elementGuidId>9b0089ad-9f71-4299-a28d-f899b7af7fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy-remove-ugate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy-remove-ugate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#policy-remove-ugate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5950c67-fbcb-4067-8053-00ec7701be8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deleteIcon</value>
      <webElementGuid>0a4c296f-9504-4e69-8c0a-66279094c729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policy-remove-ugate</value>
      <webElementGuid>87353778-8b11-42c5-92af-9e8c00ad35bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-remove-ugate&quot;)</value>
      <webElementGuid>666db440-7848-45d3-bb54-3a204504ab43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='policy-remove-ugate']</value>
      <webElementGuid>1f6c7a4f-6d3e-4beb-adc4-0dd660434e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[4]/div/div/div[3]/div[5]/div[3]/div</value>
      <webElementGuid>a68bd7ac-c670-4799-9848-3e058426ce0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geo-Proxy Server Preference is:'])[3]/following::div[2]</value>
      <webElementGuid>84851e62-4c95-4cc7-8b73-7e15d615a10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::div[16]</value>
      <webElementGuid>6d45fa10-c353-476a-9c65-496f89f6d910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow user change Geo Proxy:'])[1]/preceding::div[2]</value>
      <webElementGuid>686b2568-8122-465a-8235-50293e7a70f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div</value>
      <webElementGuid>c4bf2bc1-fb68-4f89-8720-799ce38a2e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'policy-remove-ugate']</value>
      <webElementGuid>243662b8-7551-4a43-b4c5-30e2d0cfbc1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
