<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_For data send from this ApplicationGeo-_94d955</name>
   <tag></tag>
   <elementGuidId>4b5acfe3-ad7f-440d-a493-7cc951ece6c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[4]/div/div/div[3]/div[8]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;For data send from this Application:Geo-Proxy Server Preference is: AngolaSelect&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e9654ee-8702-403d-96b5-b66ae3a0e056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-h500 col-md-10 mb-3 action-details</value>
      <webElementGuid>4b56db2e-fb4b-4178-a589-bdfe48470e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For data send from this Application:Geo-Proxy Server Preference is: Select a Region to AddAlgeriaAngolaBeninBotswanaBurkinaFasoBurundiCaboVerdeCameroonCentralAfricanRepublicChadComorosCongoRepublicDRCongoDjiboutiEgyptEquatorialGuineaEritreaEswatiniEthiopiaGabonGambiaGhanaGuineaGuineaBissauIvoryCoastKenyaLesothoLiberiaLibyaMadagascarMalawiMaliMauritaniaMauritiusMayotteMoroccoMozambiqueNamibiaNigerNigeriaReunionRwandaSaintHelenaSaoTomeandPrincipeSenegalSeychellesSierraLeoneSomaliaSouthAfricaSouthSudanSudanTanzaniaTogoTunisiaUgandaWesternSaharaZambiaZimbabweAntarcticaBouvetIslandFrenchSouthernTerritoriesHeardandMcDonaldIslandsSouthGeorgiaandtheSouthSandwichIslandsAfghanistanArmeniaAzerbaijanBahrainBangladeshBhutanBritishIndianOceanTerritoryBruneiCambodiaChinaCocosKeelingIslandsGeorgiaHongKongIndiaIndonesiaIranIraqIsraelJapanJordanKazakhstanKuwaitKyrgyzstanLaosLebanonMacaoMalaysiaMaldivesMongoliaMyanmarNepalNorthKoreaOmanPakistanPalestinePhilippinesQatarSaudiArabiaSingaporeSouthKoreaSriLankaSyriaTaiwanTajikistanThailandTurkmenistanTürkiyeUnitedArabEmiratesUzbekistanVietnamYemenAlandIslandsAlbaniaAndorraAustriaBelarusBelgiumBosniaandHerzegovinaBulgariaCroatiaCyprusCzechiaDenmarkEstoniaFaroeIslandsFinlandFranceGermanyGibraltarGreeceGuernseyHungaryIcelandIrelandIsleofManItalyJerseyKosovoLatviaLiechtensteinLithuaniaLuxembourgMaltaMoldovaMonacoMontenegroNorthMacedoniaNorwayPolandPortugalRomaniaRussiaSanMarinoSerbiaSlovakiaSloveniaSpainSvalbardandJanMayenSwedenSwitzerlandTheNetherlandsUkraineUnitedKingdomVaticanCityAnguillaAntiguaandBarbudaArubaBahamasBarbadosBelizeBermudaBonaireSintEustatiusandSabaBritishVirginIslandsCanadaCaymanIslandsCostaRicaCubaCuracaoDominicaDominicanRepublicElSalvadorGreenlandGrenadaGuadeloupeGuatemalaHaitiHondurasJamaicaMartiniqueMexicoMontserratNicaraguaPanamaPuertoRicoSaintBarthelemySaintLuciaSaintMartinSaintPierreandMiquelonSintMaartenStKittsandNevisStVincentandGrenadinesTrinidadandTobagoTurksandCaicosIslandsUSVirginIslandsUnitedStatesAmericanSamoaAustraliaChristmasIslandCookIslandsFederatedStatesofMicronesiaFijiFrenchPolynesiaGuamKiribatiMarshallIslandsNauruNewCaledoniaNewZealandNiueNorfolkIslandNorthernMarianaIslandsPalauPapuaNewGuineaPitcairnIslandsSamoaSolomonIslandsTimorLesteTokelauTongaTuvaluUSOutlyingIslandsVanuatuWallisandFutunaArgentinaBoliviaBrazilChileColombiaEcuadorFalklandIslandsFrenchGuianaGuyanaParaguayPeruSurinameUruguayVenezuela  Cancel   Add </value>
      <webElementGuid>5b3eeb9a-2670-49e6-bc08-341d7f0300ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/form[@class=&quot;el-form el-form--default el-form--label-top&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;ztn-page-h500 col-md-10 mb-3 action-details&quot;]</value>
      <webElementGuid>7265d447-07b0-4f05-887d-c5c5d184e3c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[4]/div/div/div[3]/div[8]/div[2]</value>
      <webElementGuid>1ae2ddf3-dc7f-4afb-9304-e4cd53342845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geo-Proxy Server Preference is:'])[1]/following::div[6]</value>
      <webElementGuid>93e33efa-bc1e-4cd8-b827-36a5e8f7332b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]</value>
      <webElementGuid>b7cab110-ebf0-4fcf-bff3-23ab333e7ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'For data send from this Application:Geo-Proxy Server Preference is: Select a Region to AddAlgeriaAngolaBeninBotswanaBurkinaFasoBurundiCaboVerdeCameroonCentralAfricanRepublicChadComorosCongoRepublicDRCongoDjiboutiEgyptEquatorialGuineaEritreaEswatiniEthiopiaGabonGambiaGhanaGuineaGuineaBissauIvoryCoastKenyaLesothoLiberiaLibyaMadagascarMalawiMaliMauritaniaMauritiusMayotteMoroccoMozambiqueNamibiaNigerNigeriaReunionRwandaSaintHelenaSaoTomeandPrincipeSenegalSeychellesSierraLeoneSomaliaSouthAfricaSouthSudanSudanTanzaniaTogoTunisiaUgandaWesternSaharaZambiaZimbabweAntarcticaBouvetIslandFrenchSouthernTerritoriesHeardandMcDonaldIslandsSouthGeorgiaandtheSouthSandwichIslandsAfghanistanArmeniaAzerbaijanBahrainBangladeshBhutanBritishIndianOceanTerritoryBruneiCambodiaChinaCocosKeelingIslandsGeorgiaHongKongIndiaIndonesiaIranIraqIsraelJapanJordanKazakhstanKuwaitKyrgyzstanLaosLebanonMacaoMalaysiaMaldivesMongoliaMyanmarNepalNorthKoreaOmanPakistanPalestinePhilippinesQatarSaudiArabiaSingaporeSouthKoreaSriLankaSyriaTaiwanTajikistanThailandTurkmenistanTürkiyeUnitedArabEmiratesUzbekistanVietnamYemenAlandIslandsAlbaniaAndorraAustriaBelarusBelgiumBosniaandHerzegovinaBulgariaCroatiaCyprusCzechiaDenmarkEstoniaFaroeIslandsFinlandFranceGermanyGibraltarGreeceGuernseyHungaryIcelandIrelandIsleofManItalyJerseyKosovoLatviaLiechtensteinLithuaniaLuxembourgMaltaMoldovaMonacoMontenegroNorthMacedoniaNorwayPolandPortugalRomaniaRussiaSanMarinoSerbiaSlovakiaSloveniaSpainSvalbardandJanMayenSwedenSwitzerlandTheNetherlandsUkraineUnitedKingdomVaticanCityAnguillaAntiguaandBarbudaArubaBahamasBarbadosBelizeBermudaBonaireSintEustatiusandSabaBritishVirginIslandsCanadaCaymanIslandsCostaRicaCubaCuracaoDominicaDominicanRepublicElSalvadorGreenlandGrenadaGuadeloupeGuatemalaHaitiHondurasJamaicaMartiniqueMexicoMontserratNicaraguaPanamaPuertoRicoSaintBarthelemySaintLuciaSaintMartinSaintPierreandMiquelonSintMaartenStKittsandNevisStVincentandGrenadinesTrinidadandTobagoTurksandCaicosIslandsUSVirginIslandsUnitedStatesAmericanSamoaAustraliaChristmasIslandCookIslandsFederatedStatesofMicronesiaFijiFrenchPolynesiaGuamKiribatiMarshallIslandsNauruNewCaledoniaNewZealandNiueNorfolkIslandNorthernMarianaIslandsPalauPapuaNewGuineaPitcairnIslandsSamoaSolomonIslandsTimorLesteTokelauTongaTuvaluUSOutlyingIslandsVanuatuWallisandFutunaArgentinaBoliviaBrazilChileColombiaEcuadorFalklandIslandsFrenchGuianaGuyanaParaguayPeruSurinameUruguayVenezuela  Cancel   Add ' or . = 'For data send from this Application:Geo-Proxy Server Preference is: Select a Region to AddAlgeriaAngolaBeninBotswanaBurkinaFasoBurundiCaboVerdeCameroonCentralAfricanRepublicChadComorosCongoRepublicDRCongoDjiboutiEgyptEquatorialGuineaEritreaEswatiniEthiopiaGabonGambiaGhanaGuineaGuineaBissauIvoryCoastKenyaLesothoLiberiaLibyaMadagascarMalawiMaliMauritaniaMauritiusMayotteMoroccoMozambiqueNamibiaNigerNigeriaReunionRwandaSaintHelenaSaoTomeandPrincipeSenegalSeychellesSierraLeoneSomaliaSouthAfricaSouthSudanSudanTanzaniaTogoTunisiaUgandaWesternSaharaZambiaZimbabweAntarcticaBouvetIslandFrenchSouthernTerritoriesHeardandMcDonaldIslandsSouthGeorgiaandtheSouthSandwichIslandsAfghanistanArmeniaAzerbaijanBahrainBangladeshBhutanBritishIndianOceanTerritoryBruneiCambodiaChinaCocosKeelingIslandsGeorgiaHongKongIndiaIndonesiaIranIraqIsraelJapanJordanKazakhstanKuwaitKyrgyzstanLaosLebanonMacaoMalaysiaMaldivesMongoliaMyanmarNepalNorthKoreaOmanPakistanPalestinePhilippinesQatarSaudiArabiaSingaporeSouthKoreaSriLankaSyriaTaiwanTajikistanThailandTurkmenistanTürkiyeUnitedArabEmiratesUzbekistanVietnamYemenAlandIslandsAlbaniaAndorraAustriaBelarusBelgiumBosniaandHerzegovinaBulgariaCroatiaCyprusCzechiaDenmarkEstoniaFaroeIslandsFinlandFranceGermanyGibraltarGreeceGuernseyHungaryIcelandIrelandIsleofManItalyJerseyKosovoLatviaLiechtensteinLithuaniaLuxembourgMaltaMoldovaMonacoMontenegroNorthMacedoniaNorwayPolandPortugalRomaniaRussiaSanMarinoSerbiaSlovakiaSloveniaSpainSvalbardandJanMayenSwedenSwitzerlandTheNetherlandsUkraineUnitedKingdomVaticanCityAnguillaAntiguaandBarbudaArubaBahamasBarbadosBelizeBermudaBonaireSintEustatiusandSabaBritishVirginIslandsCanadaCaymanIslandsCostaRicaCubaCuracaoDominicaDominicanRepublicElSalvadorGreenlandGrenadaGuadeloupeGuatemalaHaitiHondurasJamaicaMartiniqueMexicoMontserratNicaraguaPanamaPuertoRicoSaintBarthelemySaintLuciaSaintMartinSaintPierreandMiquelonSintMaartenStKittsandNevisStVincentandGrenadinesTrinidadandTobagoTurksandCaicosIslandsUSVirginIslandsUnitedStatesAmericanSamoaAustraliaChristmasIslandCookIslandsFederatedStatesofMicronesiaFijiFrenchPolynesiaGuamKiribatiMarshallIslandsNauruNewCaledoniaNewZealandNiueNorfolkIslandNorthernMarianaIslandsPalauPapuaNewGuineaPitcairnIslandsSamoaSolomonIslandsTimorLesteTokelauTongaTuvaluUSOutlyingIslandsVanuatuWallisandFutunaArgentinaBoliviaBrazilChileColombiaEcuadorFalklandIslandsFrenchGuianaGuyanaParaguayPeruSurinameUruguayVenezuela  Cancel   Add ')]</value>
      <webElementGuid>b81369ca-8d58-4123-afd7-2ca267671185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
