<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Geo-Proxy Server Preference is_policy-r_936737</name>
   <tag></tag>
   <elementGuidId>c6337cb3-238a-4287-bd84-a150965eacc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy-remove-preference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy-remove-preference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#policy-remove-preference</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06ce3ca7-3d86-4499-981a-7574cf21bfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deleteIcon</value>
      <webElementGuid>a69d0850-c3fd-4fe5-99e1-2f8e5843e551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policy-remove-preference</value>
      <webElementGuid>73b8ff5c-88e1-4165-b926-94159f5d5c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-remove-preference&quot;)</value>
      <webElementGuid>9bd1b47b-8b41-4a7a-8aa8-1e0cc65485aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='policy-remove-preference']</value>
      <webElementGuid>209ea023-b611-4920-b29d-b94a70ccfc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[4]/div/div/div[3]/div[3]/div[3]/div</value>
      <webElementGuid>d00c9926-c69e-43eb-8465-a8215b7155fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geo-Proxy Server Preference is:'])[3]/following::div[2]</value>
      <webElementGuid>7cf74378-28e6-410c-a246-a5b2e640091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/following::div[14]</value>
      <webElementGuid>dc7cd4c2-bde3-41ba-b643-e71affa83490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[3]/div</value>
      <webElementGuid>d3131fac-ad0a-4586-b97b-277e302325e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'policy-remove-preference']</value>
      <webElementGuid>005818d6-443f-46b1-988c-f35e864cb591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
