<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Geo-Proxy Server Preference is_region-input</name>
   <tag></tag>
   <elementGuidId>4a5ac37c-be5d-4d65-974a-37e285e24296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#region-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='region-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;please select a region&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ee7cb23-da88-464e-ab35-63884442305a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e53aab13-4537-48a2-9810-f79e9dbcbb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>please select a region</value>
      <webElementGuid>36a2d41c-8463-4135-bfbd-d11510e27eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>region-sel-btn</value>
      <webElementGuid>fadeb27a-2db1-4dcb-8eea-98f037a65b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>region-input</value>
      <webElementGuid>ad908e98-1d3b-4bcd-84a8-7bd5f5a62d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/form[@class=&quot;el-form el-form--default el-form--label-top&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;ztn-page-h500 col-md-10 action-details&quot;]/div[@class=&quot;ztn-page-h500 col-md-10 m-3 p-3 action-details-son&quot;]/div[@class=&quot;mb-2&quot;]/input[@id=&quot;region-input&quot;]</value>
      <webElementGuid>955663b6-d102-4786-8ce5-42430f33b04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='region-input']</value>
      <webElementGuid>10beb14a-3580-44b1-a413-bec629e8c694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[4]/div/div/div[3]/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>d7b99f98-7421-4c60-bdac-eabdbab386bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>3a9a9972-df52-493a-a7d2-051d714dc6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @placeholder = 'please select a region' and @id = 'region-input']</value>
      <webElementGuid>e6e1302f-3361-4a43-95e8-df833107eb60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
