<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>fdf3d1e5-b568-4568-8575-98eacdc1dce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#region-confirm-button > span.ztn-page-t400.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='region-confirm-button']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;region-confirm-button&quot;)[count(. | //*[(text() = 'Add ' or . = 'Add ')]) = count(//*[(text() = 'Add ' or . = 'Add ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16d67cb7-1ab3-4384-8120-8eb018672bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t400 text</value>
      <webElementGuid>89bbfd6a-4113-4d68-8952-58c2ed096c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add </value>
      <webElementGuid>17700026-ef6f-4f09-8e99-b8fe511bd5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region-confirm-button&quot;)</value>
      <webElementGuid>4afd250e-23b1-4f8e-a081-d2a754805622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='region-confirm-button']/span</value>
      <webElementGuid>870fb3b3-4814-40c5-bba6-d57083ee4240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[1]</value>
      <webElementGuid>e29dd6d8-034b-44af-8259-2c1f140990f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outside'])[1]/preceding::span[1]</value>
      <webElementGuid>8962efc6-e32b-44c8-8f62-b50feaed24f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>36fac93e-83fd-45c9-84f4-73f36c0ba122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/footer/button[2]/span</value>
      <webElementGuid>e28e24ed-e934-480c-87bd-86df552e50fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>ad9ecf25-d2f5-47fa-ab23-2e63fe87cd85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
