<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_China</name>
   <tag></tag>
   <elementGuidId>611009d7-3230-43f9-b158-54ec16aac60d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.el-table_7_column_37.el-table__cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='region-table']/div/div[3]/div/div/div/table/tbody/tr/td)[503]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'China' or . = 'China')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;China&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>45271d4b-68d4-4009-94e4-fe4c30d06dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-table_7_column_37 el-table__cell</value>
      <webElementGuid>2454072e-3802-4ff5-a033-5fdacef55da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a26438ba-2e0a-45b9-b5ff-c0a5ef11971a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f27337ee-f34a-41fd-8c9c-c526f0bb8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>China</value>
      <webElementGuid>8492958e-e358-48ba-9315-a6fe10a16661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-1011-24&quot;)/div[@id=&quot;region-table&quot;]/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_7_column_37 el-table__cell&quot;]</value>
      <webElementGuid>a0c03927-a852-40a4-be00-5185c32e3799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='region-table']/div/div[3]/div/div/div/table/tbody/tr/td)[503]</value>
      <webElementGuid>5710870c-2820-48a9-9ed6-732134be6d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Region to Add'])[3]/following::td[1]</value>
      <webElementGuid>c9f3a208-5dfc-4d1e-bee5-5c5230ce295c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target'])[1]/following::td[1]</value>
      <webElementGuid>644133b7-2135-47d8-864d-5d16627fe871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::td[2]</value>
      <webElementGuid>d14c6e4c-7c0f-4919-bd47-2f6532348151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/div/div[3]/div/div/div/table/tbody/tr/td</value>
      <webElementGuid>9dda7a33-2e7c-4967-a076-b87f2bf600ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'China' or . = 'China')]</value>
      <webElementGuid>62ef9d62-d3b2-4a6b-a303-90d55abe92de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
