<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_HongKong</name>
   <tag></tag>
   <elementGuidId>c2545371-e9fb-4188-8157-1ca1b680fe0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.el-table_6_column_35.el-table__cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='region-table']/div/div[3]/div/div/div/table/tbody/tr/td)[501]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'HongKong' or . = 'HongKong')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;HongKong&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b8399d27-318f-4d29-97e2-88098696258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-table_6_column_35 el-table__cell</value>
      <webElementGuid>71c5f18b-905d-42c1-ae13-2e14dfbcddba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>67282857-4e10-4947-991b-2eee07b713c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>048bf587-e8ba-4158-96e5-13c053ea8355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HongKong</value>
      <webElementGuid>bb169619-dd27-4900-aa47-2487a5eeb02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-1011-568&quot;)/div[@id=&quot;region-table&quot;]/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_6_column_35 el-table__cell&quot;]</value>
      <webElementGuid>7ac5f0b2-4fd3-4061-8230-a793775d41f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='region-table']/div/div[3]/div/div/div/table/tbody/tr/td)[501]</value>
      <webElementGuid>72ae3cce-22f5-45d8-b543-ad768b966da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Region to Add'])[2]/following::td[1]</value>
      <webElementGuid>900708f0-2b50-4b16-ae1a-ced0bd9f3257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::td[2]</value>
      <webElementGuid>905faeeb-8795-481a-b968-05990e0fcffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div[2]/div/div/div/div/div[2]/div/div[3]/div/div/div/table/tbody/tr/td</value>
      <webElementGuid>c4a3d388-4681-4d16-abe7-047df8e6214f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'HongKong' or . = 'HongKong')]</value>
      <webElementGuid>06f5bbff-52c0-49cd-95e2-9386e7aef437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
