<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StrongGate</name>
   <tag></tag>
   <elementGuidId>34644bdd-1e75-4208-b8fc-8b674dbc1d08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='identity']/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;使用StrongGate登录&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9368efd4-145d-4bbe-8c46-4f24ab2341ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t600</value>
      <webElementGuid>1eaae257-1370-40b4-a7be-13c985480d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>使用StrongGate登录</value>
      <webElementGuid>096900c0-6e84-43df-90fc-0efac5a4c70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identity&quot;)/button[@class=&quot;button-idp&quot;]/div[@class=&quot;ztn-page-t600&quot;]</value>
      <webElementGuid>a8b16cfe-e138-4782-a583-eb4045ce0ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identity']/button/div</value>
      <webElementGuid>3d455ce6-7803-4fbe-868f-d28ea77008de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StrongGate商业版试用30天，无需信用卡。StrongGate基础版永远免费。'])[1]/following::div[2]</value>
      <webElementGuid>d1f6dec7-64c3-4767-ac16-62e792577251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='免费注册StrongGate'])[1]/following::div[3]</value>
      <webElementGuid>4ed32974-77a7-4eaa-98e6-ede1b2d828db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用Microsoft登录'])[1]/preceding::div[1]</value>
      <webElementGuid>3c44c4cf-7c05-4e08-a61e-ccaa79b77c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用GitHub登录'])[1]/preceding::div[2]</value>
      <webElementGuid>45df3828-0332-4403-a711-511920aa4498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='使用StrongGate登录']/parent::*</value>
      <webElementGuid>ffd139f8-7d94-4830-af19-699e7e50a7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>d662aef0-6b9d-4269-9841-51e17aab4c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '使用StrongGate登录' or . = '使用StrongGate登录')]</value>
      <webElementGuid>4c98304e-d1cb-4b0c-a7b3-ae88d63dd323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
