<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_163-</name>
   <tag></tag>
   <elementGuidId>f3b06315-7398-4190-8223-a776d90b5323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.c-title.t.t.tts-title > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;163网易免费邮-你的专业电子邮局&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb7748cb-580c-4645-a70b-958eac2a25ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.baidu.com/link?url=jiqCyKH1m6sBJswfRZEhrWBeoSE0nE0ukhn5_hEl647&amp;wd=&amp;eqid=8dd667400032a6ef0000000666a8771b</value>
      <webElementGuid>53f05105-fa49-425a-a84c-f5105bb56fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-showurl-highlight</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8f3bcd7-5c06-4e55-8fac-69b6ffefdbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5a2ad1ce-93c4-4b31-ab13-4a12cfc970d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e379e5c4-c9fb-4908-bef7-70320a21ccd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>{&quot;F&quot;:&quot;778317EA&quot;,&quot;F1&quot;:&quot;9D73F1E4&quot;,&quot;F2&quot;:&quot;4CA6DD6A&quot;,&quot;F3&quot;:&quot;54E5243F&quot;,&quot;T&quot;:1722316571,&quot;y&quot;:&quot;FF787F7F&quot;,&quot;rsv_gwlink&quot;:&quot;1&quot;}</value>
      <webElementGuid>bdb77871-71ab-4263-bcbd-db0188ad6155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>163网易免费邮-你的专业电子邮局</value>
      <webElementGuid>aa493677-3b56-4d45-aa77-ef48be96dc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_left&quot;)/div[@id=&quot;1&quot;]/div[@class=&quot;c-container&quot;]/div[1]/h3[@class=&quot;c-title t t tts-title&quot;]/a[@class=&quot;&quot;]</value>
      <webElementGuid>922b1e30-56bb-4363-936f-778c4f47368d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/div/h3/a</value>
      <webElementGuid>b60aa73a-9dd2-404d-853d-b3d1d3d02c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='百度为您找到以下结果'])[1]/following::a[1]</value>
      <webElementGuid>dfb79d4c-bf3a-498a-8e43-7ad96c827d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::a[1]</value>
      <webElementGuid>bc6cdfd9-e5a9-4c3b-8fb8-960b969a3e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='官方'])[1]/preceding::a[1]</value>
      <webElementGuid>38dfba64-3d96-467d-b9ed-093f52dd89ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-你的专业电子邮局']/parent::*</value>
      <webElementGuid>dacbd49c-a6c9-43bd-aadf-c8673b552703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.baidu.com/link?url=jiqCyKH1m6sBJswfRZEhrWBeoSE0nE0ukhn5_hEl647&amp;wd=&amp;eqid=8dd667400032a6ef0000000666a8771b')]</value>
      <webElementGuid>4de2480d-ba7c-4d67-b416-45ae0d05f3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>6adff0e1-1758-470c-81af-c236b8a09db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.baidu.com/link?url=jiqCyKH1m6sBJswfRZEhrWBeoSE0nE0ukhn5_hEl647&amp;wd=&amp;eqid=8dd667400032a6ef0000000666a8771b' and (text() = '163网易免费邮-你的专业电子邮局' or . = '163网易免费邮-你的专业电子邮局')]</value>
      <webElementGuid>216c771e-56c9-4872-a494-abb1b4711d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
