<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_StrongGate</name>
   <tag></tag>
   <elementGuidId>4ff085f9-8990-405e-8b55-bea3a8bfb6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-idp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;$('#identity').submit()&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;使用StrongGate登录&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b3f5e85-9c0f-4069-a412-eb7232fed7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-idp</value>
      <webElementGuid>4e007640-d65d-4212-afaa-0dc62a5788f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('#identity').submit()</value>
      <webElementGuid>703a57b5-ead8-45a0-8ae4-606894c870d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    
                    使用StrongGate登录
                </value>
      <webElementGuid>ff2d6872-aac0-4042-838b-215e9694570f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identity&quot;)/button[@class=&quot;button-idp&quot;]</value>
      <webElementGuid>dd584514-503c-4d1e-a792-a0eecfba1a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;$('#identity').submit()&quot;]</value>
      <webElementGuid>a147ae27-e6c4-4248-a05d-e30c8c35d851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identity']/button</value>
      <webElementGuid>d9d0f58d-ce18-40df-bf37-c462d0eecc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StrongGate商业版试用30天，无需信用卡。StrongGate基础版永远免费。'])[1]/following::button[1]</value>
      <webElementGuid>7e6057d8-cf05-493f-ae66-91e55ade20f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='免费注册StrongGate'])[1]/following::button[1]</value>
      <webElementGuid>5b87aa3c-ebdd-4e2a-9a27-08914a006837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用Microsoft登录'])[1]/preceding::button[1]</value>
      <webElementGuid>7351dc2c-c1bf-4ab8-a87c-54cb176e0523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2c0fe9f5-32f9-46b0-bb82-11791ff493a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                    
                    使用StrongGate登录
                ' or . = '
                    
                    使用StrongGate登录
                ')]</value>
      <webElementGuid>9be428de-a85f-43ab-a2f8-8a00048b9713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
