<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>1d65b013-3f33-44de-be32-1392d7b7dfd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.page-center.ztn-page-t400 > a.a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSignin']/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;现在创建一个。&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d4c5009-ca9c-4e0a-b124-10a82c9d7b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d260c4a-2dda-4380-8973-5b8a3dade142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/idp/stronggate/signup</value>
      <webElementGuid>d3dcc9b6-3519-409e-9432-d8c9ee338c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>现在创建一个。</value>
      <webElementGuid>896594d7-6f83-46c8-a5ea-a014f71adf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignin&quot;)/div[@class=&quot;page-center ztn-page-t400&quot;]/a[@class=&quot;a&quot;]</value>
      <webElementGuid>78a63b27-50fc-4766-a713-9ce496f7611b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignin']/div[5]/a</value>
      <webElementGuid>8522da5e-2580-4dda-8b5f-bac659394ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'现在创建一个。')]</value>
      <webElementGuid>a7922506-2049-4e8d-8cae-833e96129f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='还没有StrongGate ID？'])[1]/following::a[1]</value>
      <webElementGuid>74a61b9b-6d7f-437b-8e9c-8afaea27ba91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登录'])[2]/following::a[1]</value>
      <webElementGuid>aeb525d8-5e48-4b24-846b-fb4f116850a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条款'])[1]/preceding::a[1]</value>
      <webElementGuid>45099831-ffc3-43fa-9622-25d73c880eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='现在创建一个。']/parent::*</value>
      <webElementGuid>73225f77-1346-423f-8699-728985705916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/idp/stronggate/signup')]</value>
      <webElementGuid>1b0f28ac-5983-4915-b391-1403fe25f4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>2a8a6fab-e4fd-45bc-b55c-7ddcb97f6327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/idp/stronggate/signup' and (text() = '现在创建一个。' or . = '现在创建一个。')]</value>
      <webElementGuid>ee5d8005-e145-4786-b15d-aa5c3218131a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
