<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>67388b51-d1a3-4083-95f9-e768db9e8572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-h300.label-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='dosignup']/div[2]/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;用户名：&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>236f2419-50c6-468c-a436-7c0b95c96608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-h300 label-left</value>
      <webElementGuid>fc3e53e2-aef8-455d-b9be-8b725fde2552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>用户名：</value>
      <webElementGuid>db46b0a5-a7d0-4817-89e6-41eb7d6d3da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosignup&quot;)/div[2]/label[1]/div[@class=&quot;ztn-page-h300 label-left&quot;]</value>
      <webElementGuid>7a1a8c0e-da22-4cd2-8454-e83b559783c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dosignup']/div[2]/label/div</value>
      <webElementGuid>7f145b26-fb97-4463-af9b-dc57ea0731cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新的StrongGate身份帐户'])[1]/following::div[2]</value>
      <webElementGuid>b377c8ce-92ff-466c-ab2a-437e62fbb6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='注册'])[1]/following::div[3]</value>
      <webElementGuid>1d1ddc1b-39a3-4ece-8afa-697fba93f2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='电子邮件地址作为您的登录ID：'])[1]/preceding::div[2]</value>
      <webElementGuid>0fa93a8b-d066-4d2f-81d0-904c05db2b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='将向您的电子邮件地址发送一封带有一次性密码的电子邮件。'])[1]/preceding::div[4]</value>
      <webElementGuid>7b0071a5-0551-42a8-8cf7-24c898d19dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='用户名：']/parent::*</value>
      <webElementGuid>d003052b-292e-4ee8-83cc-d2624c268013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>31720e6e-1b15-4675-9c1d-c0ea5e2ec456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '用户名：' or . = '用户名：')]</value>
      <webElementGuid>b0a19349-3508-40c7-a3cb-e95f35c8f149</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
