<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__teamDomain</name>
   <tag></tag>
   <elementGuidId>3111a1ef-3083-438d-9c3a-f74464c8a6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-team-domain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-team-domain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;团队域：&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8634d192-6db2-4971-87a8-1740ad804b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-team-domain</value>
      <webElementGuid>fa08e4ed-b715-42e3-92d9-53745834c1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teamDomain</value>
      <webElementGuid>0a700005-73d9-48c1-a1ee-109779732305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b1997b9-24a5-4985-8d63-1e88e66eaedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>团队域：</value>
      <webElementGuid>57ccf9d5-2c20-4ee4-8a3f-73fc44df8bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>teamDomainFocus()</value>
      <webElementGuid>30d52966-5df9-4a02-92d6-b4e1714d0db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>verification()</value>
      <webElementGuid>1118d839-431a-4c26-9873-1e49f5ae5b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-team-domain&quot;)</value>
      <webElementGuid>048da2cb-ce00-4aff-a3e5-47d0a1ff3fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-team-domain']</value>
      <webElementGuid>6f42f955-48d7-4c8a-abff-61f244b24c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignUp']/div[6]/input</value>
      <webElementGuid>f37578ce-3a2b-44e3-bd62-fa08ff04f433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>d55f29ce-291d-4cef-b8ea-3d48e5bcc930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txt-team-domain' and @name = 'teamDomain' and @placeholder = '团队域：']</value>
      <webElementGuid>5258f990-d80f-48f2-a12b-8b4d97a48636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
