<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_test1b895a9test.com</name>
   <tag></tag>
   <elementGuidId>4c1e8c6a-c002-4380-ab86-db70083dd6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-wrapper']/div[2]/div/div[4]/div/div/div/div/div/div[3]/div/div/div/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.el-table_7_column_37.el-table__cell > div.cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;test1b895a9@test.com&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90056599-e5d9-4de0-ae58-bc919d2b12d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>f8421ce4-888f-44ef-b11f-9eb6d919f89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test1b895a9@test.com</value>
      <webElementGuid>f8288f04-088e-4864-b000-ad05f06cbf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card ztn-table&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;el-table--fit el-table--enable-row-hover el-table--enable-row-transition el-table el-table--layout-fixed ztn-common-table mb-4 is-scrolling-none&quot;]/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_7_column_37 el-table__cell&quot;]/div[@class=&quot;cell&quot;]</value>
      <webElementGuid>0d171a52-fb59-4e3f-a4e7-772ea933628c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[4]/div/div/div/div/div/div[3]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>cfe034f9-d238-4240-be03-1cfec1f57fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test1b895a9@test.com']/parent::*</value>
      <webElementGuid>56cefbc2-df87-441c-9d5b-c23669568c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>2160fd67-a116-4c4f-8df1-6035620aebaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'test1b895a9@test.com' or . = 'test1b895a9@test.com')]</value>
      <webElementGuid>c9ba3e4f-8364-4811-b5f8-ad5f601d9394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
