<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StrongGate</name>
   <tag></tag>
   <elementGuidId>1e5cf68d-04ae-4c9e-aa81-5e2fa50d06c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='identity']/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t600</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;使用StrongGate登录&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ec1a608-1c69-4077-a738-0ccfa0ad59be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t600</value>
      <webElementGuid>93817bdd-25c5-4586-a445-e4278f33e628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>使用StrongGate登录</value>
      <webElementGuid>4b2dfbc1-501f-423b-9aca-d04a7d8b6b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identity&quot;)/button[@class=&quot;button-idp&quot;]/div[@class=&quot;ztn-page-t600&quot;]</value>
      <webElementGuid>835f5c29-09c8-4565-bc2f-e776832a68ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identity']/button/div</value>
      <webElementGuid>08010dca-7e04-46d9-a081-ba8d0b510e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StrongGate商业版试用30天，无需信用卡。StrongGate基础版永远免费。'])[1]/following::div[2]</value>
      <webElementGuid>5a3704bf-b14e-47a0-921f-916b4ac2647b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='免费注册StrongGate'])[1]/following::div[3]</value>
      <webElementGuid>9d738a98-254f-4114-9f38-a056d9eb5460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用Microsoft登录'])[1]/preceding::div[1]</value>
      <webElementGuid>8e9d486f-665f-4a34-bd57-2e43d69424d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用GitHub登录'])[1]/preceding::div[2]</value>
      <webElementGuid>09a527fe-d8ce-406f-947a-aebd4d6a1822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='使用StrongGate登录']/parent::*</value>
      <webElementGuid>bab8229c-e0a9-430a-9923-b177fd39620e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>9b8126b0-d098-4619-8ab9-3e32011d9882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '使用StrongGate登录' or . = '使用StrongGate登录')]</value>
      <webElementGuid>e683659d-02a9-4713-b1bc-610b0fdbf78f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
