<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_StrongGate</name>
   <tag></tag>
   <elementGuidId>8deec6f9-ad5f-4f4b-8779-99125167ef20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='identity']/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t600</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;使用StrongGate登录&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f114bc4-924d-4d8b-a8ee-dd78fcdc0de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t600</value>
      <webElementGuid>b9238626-4c06-42fc-b834-56e9418b52ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>使用StrongGate登录</value>
      <webElementGuid>27f63c84-0f85-4798-b086-802d1dd1b02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identity&quot;)/button[@class=&quot;button-idp&quot;]/div[@class=&quot;ztn-page-t600&quot;]</value>
      <webElementGuid>f5e5c910-5e90-442b-aacc-cbf093237a75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='identity']/button/div</value>
      <webElementGuid>931c6cce-004c-4ebf-8471-07dfbeb62109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test333'])[3]/following::div[2]</value>
      <webElementGuid>01b82485-c9d8-4ae7-9c1c-05d22fa8c0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用Microsoft登录'])[1]/preceding::div[1]</value>
      <webElementGuid>86d5b15f-4e8f-48d4-b762-1b0472eaad61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用GitHub登录'])[1]/preceding::div[2]</value>
      <webElementGuid>ddf13604-4c9e-470a-bea2-88161e19bd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='使用StrongGate登录']/parent::*</value>
      <webElementGuid>f4c82dd0-44e9-414b-b485-6915b0b87a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>6f690027-d477-4ae5-a1ba-85c932499135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '使用StrongGate登录' or . = '使用StrongGate登录')]</value>
      <webElementGuid>b89358fc-0428-4846-9770-b6bb35458a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
