<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ID</name>
   <tag></tag>
   <elementGuidId>5ec4f1b3-4d19-4526-8e58-25121bc3076b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSignin']/div[2]/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-h300.label-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;登录ID：&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11cac5e6-450e-49d9-b28c-169844d52c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-h300 label-left</value>
      <webElementGuid>593ab6e3-e879-4fdf-8080-24c6116f82c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登录ID：</value>
      <webElementGuid>c3bb30e4-1884-4840-aa19-92efbc8fb7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignin&quot;)/div[2]/label[1]/div[@class=&quot;ztn-page-h300 label-left&quot;]</value>
      <webElementGuid>14fa8f37-38f2-4e6b-96f6-007ae5dc6357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignin']/div[2]/label/div</value>
      <webElementGuid>a4d148d9-9a2e-4e1c-9fed-a9be178513fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StrongGate'])[1]/following::div[2]</value>
      <webElementGuid>62572313-0587-48c9-b4d3-9d566f1aeb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='以继续'])[1]/following::div[2]</value>
      <webElementGuid>b2946470-d905-4e6a-8c4b-16bc03efb037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='密码:'])[1]/preceding::div[2]</value>
      <webElementGuid>702e0254-ec47-496d-b1c1-0a7cc4d24fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示'])[1]/preceding::div[4]</value>
      <webElementGuid>7d775cd8-b7ae-41e1-b199-44881f9fdffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登录ID：']/parent::*</value>
      <webElementGuid>797548d1-02e7-4c43-bdd1-93dfcfeea2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>5e7123d3-48e5-4362-9c80-f9006751a79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '登录ID：' or . = '登录ID：')]</value>
      <webElementGuid>3efdb733-8fad-4eea-908b-ec61c8d407d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
