<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_confirm</name>
   <tag></tag>
   <elementGuidId>93a49cce-0fb1-4c71-acd9-51c2349a0a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='location-confirm']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location-confirm > span.ztn-page-t400.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>826322d6-eaa3-4106-a26b-ec8811afe267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t400 text</value>
      <webElementGuid>06caa155-6cf9-435c-92c4-0701c9716ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>confirm </value>
      <webElementGuid>6489e7a1-32a9-447d-932e-d0520a12e037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location-confirm&quot;)/span[@class=&quot;ztn-page-t400 text&quot;]</value>
      <webElementGuid>d95e895c-70a1-45b3-a4a2-515e0b1dd318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='location-confirm']/span</value>
      <webElementGuid>284d40c4-f4ef-407a-9515-e9d93914b970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel'])[1]/following::span[1]</value>
      <webElementGuid>8ea4a09b-a230-4033-ad7f-48a64ee4a93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[2]/following::span[6]</value>
      <webElementGuid>e2e8c405-dc64-4d8d-b91b-afdba58fda16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team: test333(3609796866985697280) , Continent: NA-9999999(9999999) , Region: NA-9999999(9999999)'])[1]/preceding::span[1]</value>
      <webElementGuid>c9e58b09-e064-4dac-8404-b416cb72f9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/preceding::span[2]</value>
      <webElementGuid>8e6560f6-371e-4561-a771-4cc684aa1fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='confirm']/parent::*</value>
      <webElementGuid>a512bee9-794c-4c2f-a077-193c000dd2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]/span</value>
      <webElementGuid>75b8d9dd-3828-470c-a2e0-8dd7b09e8dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'confirm ' or . = 'confirm ')]</value>
      <webElementGuid>5c15a464-d2a3-47c3-afae-2276121adcc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
