<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Select</name>
   <tag></tag>
   <elementGuidId>b9917a0f-9607-430b-bd7b-af5a817f3729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-table']/div/div[3]/div/div/div/table/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.el-table_2_column_10.el-table__cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Select&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>48309a69-e8cb-491e-8234-b4b58630374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-table_2_column_10 el-table__cell</value>
      <webElementGuid>f1d41442-e2b8-4c4c-bf1b-1564d02a85f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c407ebb5-6137-4b07-9cb9-ea6b2e9c41f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5885a04c-99b6-48ec-83f5-19cbfcf4d883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Select </value>
      <webElementGuid>baeab798-2449-4fbb-b451-fae1562868b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-table&quot;)/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row editable-row&quot;]/td[@class=&quot;el-table_2_column_10 el-table__cell&quot;]</value>
      <webElementGuid>d31c7500-a38d-46b3-ba1d-946ae3d88282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-table']/div/div[3]/div/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>b309fc4e-7111-4fd2-8c93-c90d9337b084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>6165850e-0157-4585-8eb8-ea1da7c60cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '  Select ' or . = '  Select ')]</value>
      <webElementGuid>b5af8f2b-cfe9-440e-a780-fb64aa6df463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
