<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>92b8c90a-c845-48c0-a1f4-ee872f0faf4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSignin']/div[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-center.ztn-page-t400 > a.a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;现在创建一个。&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d52041db-8e63-4ba6-8da4-1099f1536eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b1b8864-53e8-47f3-8a2e-8417a223df52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/idp/stronggate/signup</value>
      <webElementGuid>ab2f5e66-6212-4f34-bb87-7233b73e7c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>现在创建一个。</value>
      <webElementGuid>1acb23c4-1d88-417d-ae91-4474b00a595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignin&quot;)/div[@class=&quot;page-center ztn-page-t400&quot;]/a[@class=&quot;a&quot;]</value>
      <webElementGuid>6f84be67-5144-4c3f-8411-c2c5c875a8fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignin']/div[5]/a</value>
      <webElementGuid>eefb915c-e2bd-48b3-92a5-27ad9f74b5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'现在创建一个。')]</value>
      <webElementGuid>46bd708f-068b-42b6-950d-dd3f0cd8e53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='还没有StrongGate ID？'])[1]/following::a[1]</value>
      <webElementGuid>18ce1880-4fb5-4bc7-8f90-860c0eaa6663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登录'])[2]/following::a[1]</value>
      <webElementGuid>f2ff0e55-7b1c-4efb-aaa5-34326f828085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条款'])[1]/preceding::a[1]</value>
      <webElementGuid>c1b64827-5387-4b87-86f8-5b35b94e554c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='现在创建一个。']/parent::*</value>
      <webElementGuid>c089d0aa-2302-4dac-ad73-4d0c4efb8c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/idp/stronggate/signup')]</value>
      <webElementGuid>5f4528f1-dc7c-422f-9506-4cc0db94a973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>d1b364f1-08df-4522-8ac9-35500bbf038d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/idp/stronggate/signup' and (text() = '现在创建一个。' or . = '现在创建一个。')]</value>
      <webElementGuid>668562c2-581e-402b-bf5b-72719795680b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
