<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__t</name>
   <tag></tag>
   <elementGuidId>24cd77f6-14d0-4db4-b12c-e5701e1bcd0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-team-domain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-team-domain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;团队域名&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e879c698-251a-414d-b892-4815dc15e802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-team-domain</value>
      <webElementGuid>c82513b6-92ee-4f1c-8895-5e21889c236c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>f52c64d9-13d5-4f83-859e-16785a7aa1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08478397-c71b-4d12-862a-ab0c19075895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>团队域名</value>
      <webElementGuid>0765b4c4-5af8-409d-9894-62e3a3b6f186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>monitorDomain()</value>
      <webElementGuid>d472f099-b177-416f-ac86-de551c853bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>onSignIn(event)</value>
      <webElementGuid>32449c29-7cd9-466d-b495-add7ba436603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-team-domain&quot;)</value>
      <webElementGuid>6a4b8d48-e84a-411c-9bd0-dc0a5ec5ce3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-team-domain']</value>
      <webElementGuid>0d56c64a-8882-499a-be43-64b09ef1941e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignIn']/div[4]/input</value>
      <webElementGuid>4cbc872e-5a86-4baf-afaf-6b56db2eb1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>e7ea89a9-07f6-4028-91b1-91bd5bb2600a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txt-team-domain' and @name = 't' and @placeholder = '团队域名']</value>
      <webElementGuid>c3fd41dc-0165-47d2-ad44-08a7e4b19338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
