<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__search-enable</name>
   <tag></tag>
   <elementGuidId>892a5fd3-ebbd-49bc-8d46-5b832ae97421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-enable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-policy']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.search-enable</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d6bfc53-1a94-48c7-aa02-f44e51e83b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-enable</value>
      <webElementGuid>41bccbf0-d557-4e3e-85ab-c43855fb0a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@id=&quot;search-policy&quot;]/div[@class=&quot;search-box me-2&quot;]/div[@class=&quot;search-enable&quot;]</value>
      <webElementGuid>13061e34-4adb-4334-9d8c-78273dfa8758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-policy']/div/div</value>
      <webElementGuid>59e62744-79a6-4f97-abfa-816ef5da6be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::div[5]</value>
      <webElementGuid>f3d879b4-2f64-415f-9173-92d0e923ef9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Policy'])[1]/preceding::div[1]</value>
      <webElementGuid>38ee3cc7-3737-44d8-821c-45521a5b067e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div</value>
      <webElementGuid>71ad5376-43aa-427f-8ab2-12e0f9534d44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
