<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__search-policy</name>
   <tag></tag>
   <elementGuidId>fe46f861-efa0-4756-be22-45baa7e2621c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-enable > #search-policy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-policy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77dd70a6-920d-418f-bae4-b39413a0cf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c76568f-5429-4a65-9147-59f709e0414e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-policy</value>
      <webElementGuid>ac0dc329-1179-4241-a208-9bff70d2e5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>ee3e6d71-83f5-46cf-b1da-2d50b22a1d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@id=&quot;search-policy&quot;]/div[@class=&quot;search-box me-2&quot;]/div[@class=&quot;search-enable&quot;]/input[@id=&quot;search-policy&quot;]</value>
      <webElementGuid>8c445a3c-c7f8-4552-b731-9f6a21ae367d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-policy']</value>
      <webElementGuid>816dfa22-c924-4c36-a07d-1a401b0f5dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-policy']/div/div/input</value>
      <webElementGuid>a67ef1c5-1407-4fe8-8ac7-10a11edffc52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>4858c65a-df5e-4dd4-b210-09bbe651bd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-policy' and @placeholder = 'Search...']</value>
      <webElementGuid>def8d23f-b6aa-478e-aa63-a3dad20b5701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
