<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_con-001</name>
   <tag></tag>
   <elementGuidId>d1960927-2e18-4d7e-bada-6d5364c7648a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-id-4322-44']/div[2]/div/div[3]/div/div/div/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.el-table_10_column_66.table-enable-row.el-table__cell > div.cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;con-001&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d20cc349-d450-4ab8-a8f6-08316eb53933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>33d7706d-fdd8-4e39-8a0b-6545328ade6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>con-001</value>
      <webElementGuid>1bdfc22a-b8e4-4dbb-bed9-61ca07762706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-4322-44&quot;)/div[@class=&quot;el-table--fit el-table--fluid-height el-table--enable-row-hover el-table--enable-row-transition el-table el-table--layout-fixed ztn-common-table is-scrolling-none&quot;]/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_10_column_66 table-enable-row el-table__cell&quot;]/div[@class=&quot;cell&quot;]</value>
      <webElementGuid>4610b84e-9eb9-42d6-ba58-039eaf21e131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-id-4322-44']/div[2]/div/div[3]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>40022362-8e23-4df1-99c2-93dfddcc3860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items: 1-10'])[1]/preceding::div[8]</value>
      <webElementGuid>600d49b8-e1ba-4b1f-9a06-2ca24a9493b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='con-001']/parent::*</value>
      <webElementGuid>3c01ef0e-4a8b-49bf-a8aa-01d33a893546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>c9e56c6c-0dfd-4aa6-adeb-dcb6646cfb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'con-001' or . = 'con-001')]</value>
      <webElementGuid>a785e242-e91c-4b5e-823f-d427dc4f4536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
