<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Location Token Server</name>
   <tag></tag>
   <elementGuidId>edee7f9e-5ade-4d8f-92b0-3bbf4d2f7384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ugate-location-token</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ugate-location-token']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ugate-location-token</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd54ec70-0c8b-4f44-8844-7d3ed428cd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3 customize text custom</value>
      <webElementGuid>de1280b2-b6a2-4960-848a-66760d91c4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ugate-location-token</value>
      <webElementGuid>a1674706-7cba-44f5-8747-1a6efa4e7568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Location Token Server </value>
      <webElementGuid>4d1a90b4-72ee-4f6b-96f2-ee0aa3671b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-location-token&quot;)</value>
      <webElementGuid>46d0a05a-9f64-4f4c-9f04-cf8c7ba21d4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ugate-location-token']</value>
      <webElementGuid>a4269514-9cfa-4304-8ee5-3c1e4e5805a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div[2]/div[2]/div[2]/form/div/div</value>
      <webElementGuid>33464cf2-1dde-49f5-be2c-c002d198f09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uGate as Proxy and Filtering Server. Require Proxy Server function too'])[1]/following::div[2]</value>
      <webElementGuid>d0c3c722-1794-4938-abaa-5af01506c9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtering Server'])[1]/following::div[4]</value>
      <webElementGuid>e3233933-e306-45c6-8bb7-7aee2377489b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GEO Proxy'])[2]/preceding::div[16]</value>
      <webElementGuid>e452d20b-753f-40eb-a0d4-4654a066df95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div</value>
      <webElementGuid>6449a9c0-1835-49c4-afe1-4630c56d08ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ugate-location-token' and (text() = '   Location Token Server ' or . = '   Location Token Server ')]</value>
      <webElementGuid>1d77e0ea-6486-44b2-90f4-0aa434416d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
