<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filtering Server</name>
   <tag></tag>
   <elementGuidId>e91735ce-6095-48b7-9d92-883b326cacc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ugate-firewall</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ugate-firewall']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ugate-firewall</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8eef4816-b7d3-495e-8d29-46d61dc68144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3 customize text custom</value>
      <webElementGuid>97976ac2-7813-4d47-89de-aaf1ef486824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ugate-firewall</value>
      <webElementGuid>d97cf251-cb5d-4de5-96b9-fa4c9ed42fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Filtering Server </value>
      <webElementGuid>44f5a98f-de18-4edb-ac6d-af88e860b1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-firewall&quot;)</value>
      <webElementGuid>02c80d53-ba33-4148-8fe4-ffde205933b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ugate-firewall']</value>
      <webElementGuid>4b486d39-98d4-4e2b-ac69-900a1511d337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>adc1a185-d958-4053-8091-1d51be234a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uGate as Proxy Server'])[1]/following::div[2]</value>
      <webElementGuid>8a55c816-52d6-4052-ba26-733cd2de4a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Proxy'])[1]/following::div[4]</value>
      <webElementGuid>33932b34-0429-49d1-9031-177042bfcb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uGate as Proxy and Filtering Server. Require Proxy Server function too'])[1]/preceding::div[3]</value>
      <webElementGuid>0205fc38-b450-4fb0-a68b-3b2aa26cef72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>7dbb8d34-5932-412c-a704-78623244e910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ugate-firewall' and (text() = '   Filtering Server ' or . = '   Filtering Server ')]</value>
      <webElementGuid>014ae52c-9d79-4e67-bb12-d431786e8be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
