<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_offline_operator</name>
   <tag></tag>
   <elementGuidId>cae36465-020f-43ee-90cf-0f808afc46e1</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operator</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'assets/img/dots-three-outline-vertical.10d331c2.svg' and @id = 'operator']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='operator']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;u-12691be u-desc12691be YES offline 0&quot;i] >> #operator</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd34b8e1-53b9-4dc5-9f5a-718ed9e062b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/dots-three-outline-vertical.10d331c2.svg</value>
      <webElementGuid>917fcc5c-b60e-4b41-8887-fb54561d633e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img el-tooltip__trigger el-tooltip__trigger</value>
      <webElementGuid>a2ab6ebd-8b7c-42d4-8ab1-578e5ea00847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operator</value>
      <webElementGuid>1147632b-990c-4539-a77a-b498ff49e29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c63640b-76c6-459c-a576-a7778c8faddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>daadae82-3bb7-489a-861c-3a3ac00678b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>el-id-8991-45</value>
      <webElementGuid>5c173714-d916-413a-bc62-1e84cea042ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2caf1751-e851-46d1-940e-fa152cb0d1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>387177eb-6631-4f25-8bc0-e4c6f5e3f8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-table&quot;)/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_7_column_51 is-right el-table__cell&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;el-dropdown&quot;]/img[@id=&quot;operator&quot;]</value>
      <webElementGuid>79d54f8f-c994-433c-a0dd-bf868f249ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='operator']</value>
      <webElementGuid>d56d2f6c-335c-42fc-a6e1-395eb90bc291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ugate-table']/div/div[3]/div/div/div/table/tbody/tr/td[9]/div/div/img</value>
      <webElementGuid>e03e373c-2df9-4564-ba39-232df9569f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/img</value>
      <webElementGuid>57bda5d1-788c-4c50-94fe-031e635a40fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/img/dots-three-outline-vertical.10d331c2.svg' and @id = 'operator']</value>
      <webElementGuid>ce3f5761-d512-493e-853f-e947302f532b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
