<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_offline_el-id-8991-20</name>
   <tag></tag>
   <elementGuidId>e3e68630-aabe-4edc-83b7-fdcf6bc51fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-8991-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='el-id-8991-20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#el-id-8991-20</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>adcd8d6e-175f-4dff-b655-f3511d5ed87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/dots-three-outline-vertical.10d331c2.svg</value>
      <webElementGuid>b9bafbbd-9869-429f-9d28-ed74b3f651be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img el-tooltip__trigger el-tooltip__trigger</value>
      <webElementGuid>7eb46775-592e-4470-b3b0-5e0f134d7074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-id-8991-20</value>
      <webElementGuid>08e8a216-582a-4262-bb6b-89076d981689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0250b013-d810-46f6-955c-67374282c676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32639756-07d7-435a-89d5-98ec53a73ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>el-id-8991-21</value>
      <webElementGuid>87e75736-ee9e-42d3-86cf-4d97227d43fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60e8bf10-8099-4020-8517-b57907e81ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>74c1c8ca-1348-457a-a5ff-bb348db5527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-8991-20&quot;)</value>
      <webElementGuid>7b0b6dcb-0395-4d50-a802-d2cee645cedd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='el-id-8991-20']</value>
      <webElementGuid>2469f368-07a9-47e1-8b0a-35122d2dae81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ugate-table']/div/div[3]/div/div/div/table/tbody/tr/td[9]/div/div/img</value>
      <webElementGuid>048015d6-bda4-47eb-a701-cf1a802cb045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/img</value>
      <webElementGuid>14cedae9-6aa2-408d-ae89-5915ac1e19dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/img/dots-three-outline-vertical.10d331c2.svg' and @id = 'el-id-8991-20']</value>
      <webElementGuid>b1fba2a5-1305-44bb-a724-a258bf0a6b9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
