<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mac address_ugate-mac-values</name>
   <tag></tag>
   <elementGuidId>384cd6d4-2da1-4f80-8bdc-01d0a563dcd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ugate-mac-values</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ugate-mac-values']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ugate-mac-values</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa2d5d2f-b69d-4c24-bb23-3df97e8eda23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3822d084-dac3-44dd-950d-6cf0feb89e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ugate-mac-values</value>
      <webElementGuid>62299c32-3335-4330-b21e-a506a5f32017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-mac-values&quot;)</value>
      <webElementGuid>14193fe7-8191-4225-9e9e-1d986d4ef0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ugate-mac-values']</value>
      <webElementGuid>955d4574-0b81-4f54-aa74-1652e16d8330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div[3]/div[2]/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>b09fc161-aab8-4fb3-9e39-50d9b7af9327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>6143213d-80cc-4401-85a1-ec4d8ac9234c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ugate-mac-values']</value>
      <webElementGuid>b490dc5e-7685-4888-8cc9-8b8edc014417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
