<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ip Range or one Ip address_ugate-ip-values</name>
   <tag></tag>
   <elementGuidId>684b3fa4-de83-49b1-9ff6-0c0dca9ee608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ugate-ip-values</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ugate-ip-values']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g. 192.0.1.11/16, 172.16.0.0-172.16.0.233&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bbc810e-e097-44cb-841d-a1782864970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 192.0.1.11/16, 172.16.0.0-172.16.0.233</value>
      <webElementGuid>495d3669-d36f-4e81-82f5-bbffecc70ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7df85b2a-efee-42b8-a46f-7e9c008eb25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ugate-ip-values</value>
      <webElementGuid>6a1d4394-76e0-4d93-868e-10f24cfa66db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-ip-values&quot;)</value>
      <webElementGuid>e134cd5c-e662-4dcc-9b1a-43a7763b1e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ugate-ip-values']</value>
      <webElementGuid>3ba4bdbc-98e5-48bc-894a-a1003ee04052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div[3]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>4b78bae2-ab95-4e2a-987e-3cb7a5751b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>8459ea32-f6a6-47b7-ae58-ddd6717cfaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g. 192.0.1.11/16, 172.16.0.0-172.16.0.233' and @id = 'ugate-ip-values']</value>
      <webElementGuid>02a95b9f-6e43-49de-8ba8-77280b061f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
