<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Token Generated and Exit</name>
   <tag></tag>
   <elementGuidId>0cf1d68c-6bc1-4d89-b4aa-3d7ec2203698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ztn-page-t400.text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ugate-edit-button&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ugate-token-button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Token Generated and Exit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>741215b7-b674-4957-8e82-eb4954d09f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t400 text</value>
      <webElementGuid>76b2cc8a-ffa3-4945-9936-cfcc0d8dcca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Token Generated and Exit </value>
      <webElementGuid>d5d73bf4-4d7e-4469-84dd-d8bda9be47fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-token-button&quot;)</value>
      <webElementGuid>8b2c0c6a-cb0c-417b-a0ba-bcc49743745d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ugate-token-button']/span</value>
      <webElementGuid>72f841b3-b502-44a3-a875-377ac6cf3a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[1]</value>
      <webElementGuid>be5c90e0-3918-4587-81f4-611921662761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/preceding::span[2]</value>
      <webElementGuid>08f6c688-20b8-4251-8709-040191c00be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Token Generated and Exit']/parent::*</value>
      <webElementGuid>626a459f-3db3-475f-8e67-c641a2221b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>02fdb61c-1429-47ac-89b9-2fd08a2fde6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Token Generated and Exit ' or . = 'Token Generated and Exit ')]</value>
      <webElementGuid>91ac51c0-e33c-427e-8769-e0e49def439c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
