<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copy Token</name>
   <tag></tag>
   <elementGuidId>a4018e1f-8dbc-44fa-a128-a5d4b2250efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ugate-copy-token > span > span.ztn-page-t150</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ugate-copy-token']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Copy Token&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>839ea3f1-0126-4678-9907-325749a93d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t150</value>
      <webElementGuid>84ade8f9-259b-4140-9921-539c72826174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Copy Token </value>
      <webElementGuid>9de65581-24b5-4484-97e3-73d5aafe4469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ugate-copy-token&quot;)/span[1]/span[@class=&quot;ztn-page-t150&quot;]</value>
      <webElementGuid>e80bf76c-385c-4119-a691-16aadc3a397c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ugate-copy-token']/span/span</value>
      <webElementGuid>beb3e416-bce6-4ef5-a685-c3b3faad4976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uGate Server Deployment Token'])[1]/following::span[2]</value>
      <webElementGuid>ab090bb4-bdcb-42ae-8b5a-2aeef3087c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step4. Generate Deployment Token:'])[1]/following::span[2]</value>
      <webElementGuid>0a915339-535e-4f26-bb40-e0fad2290943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step5. Download the software:'])[1]/preceding::span[1]</value>
      <webElementGuid>c35a2665-e143-47df-ad5d-6f0fefb5bf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Windows x64: suitable for windows x64 or 32bit, from Windows 8 and up'])[1]/preceding::span[1]</value>
      <webElementGuid>8115c234-f19f-4c4b-ac6b-10128b031dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button/span/span</value>
      <webElementGuid>6c9fbe5b-3826-4650-a76d-6e0b79349657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  Copy Token ' or . = '  Copy Token ')]</value>
      <webElementGuid>174d004c-76ed-47b5-9749-31668c03ab48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
