<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_offline_operator</name>
   <tag></tag>
   <elementGuidId>262731dc-86f5-4a88-9d23-d692417400ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='operator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;con-002 desc-002 Docker YES offline&quot;i] >> #operator</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d5bf41c-3cbb-47e1-bd5f-5fb58bfe05aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/dots-three-outline-vertical.10d331c2.svg</value>
      <webElementGuid>119415e7-3ea6-4acc-8464-cbf21796dc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img el-tooltip__trigger el-tooltip__trigger</value>
      <webElementGuid>2223705d-09a9-4b40-9a12-cef7ece34ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operator</value>
      <webElementGuid>02db9e9f-1403-4fec-b6ca-339762c49193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2579ab9-35c8-4c17-b651-baa95f8ac0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4bc3755-a4e1-4510-8334-f88c85260c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>el-id-2007-31</value>
      <webElementGuid>b87129e6-4783-4d4b-97b2-51fc8a8a4383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47b2452b-da8a-4eae-81ef-4b0b2c78e34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>19d2a1e4-03a1-4afb-9d93-42f843766409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card ztn-table&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;el-table--fit el-table--enable-row-hover el-table--enable-row-transition el-table el-table--layout-fixed ztn-common-table mb-2 is-scrolling-none&quot;]/div[@class=&quot;el-table__inner-wrapper&quot;]/div[@class=&quot;el-table__body-wrapper&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_8_column_49 is-right el-table__cell&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;el-dropdown&quot;]/img[@id=&quot;operator&quot;]</value>
      <webElementGuid>11a25722-b940-4004-9876-18069fc00e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='operator']</value>
      <webElementGuid>521007bf-9b12-486f-988b-72c2e65e283d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[3]/div/div/div/div/div/div[3]/div/div/div/table/tbody/tr/td[8]/div/div/img</value>
      <webElementGuid>c624aa9d-9f35-4d1a-a325-0acb08fdb7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/img</value>
      <webElementGuid>71f70ecf-68bc-45ee-82b4-159d1bd67242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/img/dots-three-outline-vertical.10d331c2.svg' and @id = 'operator']</value>
      <webElementGuid>6b3b4d4e-a91e-472f-b003-75195eef8359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
