<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__search-connector</name>
   <tag></tag>
   <elementGuidId>bff4f192-1ba0-41f5-9e7d-f8702cc24e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-enable > #search-connector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-connector']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58814a5f-026e-4d5b-af6b-cc016470649f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a3d1554-fa39-416b-927b-ccb90a98e616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-connector</value>
      <webElementGuid>d1a7529e-b394-4411-bfcd-71803185e92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>e572fe86-e4f1-4426-a20f-76673ae1d61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@id=&quot;search-connector&quot;]/div[@class=&quot;search-box me-2&quot;]/div[@class=&quot;search-enable&quot;]/input[@id=&quot;search-connector&quot;]</value>
      <webElementGuid>c0602ddf-dafa-443a-9f80-80337c3c34a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-connector']</value>
      <webElementGuid>bb1fe03d-7cab-4e55-b36d-b1ac94aed12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-connector']/div/div/input</value>
      <webElementGuid>c7125336-c2af-45c0-bb3e-381956883d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>e3584dcc-80c2-4c48-9413-b73a5bf3bb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-connector' and @placeholder = 'Search...']</value>
      <webElementGuid>6ef300e2-bd22-4b66-8133-36519d9e1aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
