<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>84d570cb-8f0d-4aed-8467-43abc536ef10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSignin']/div[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-center.ztn-page-t400 > a.a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;现在创建一个。&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cef541e3-983a-43a0-adbf-4bc869665119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f6d03c5-ef0f-4478-b387-e9ee72bd41f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/idp/stronggate/signup</value>
      <webElementGuid>4e3f0d1d-0d0c-45c6-9ae4-9eb053b282ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>现在创建一个。</value>
      <webElementGuid>41501c19-515e-4853-9027-b587d24c7eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignin&quot;)/div[@class=&quot;page-center ztn-page-t400&quot;]/a[@class=&quot;a&quot;]</value>
      <webElementGuid>7b86e99b-a9ad-4400-9b87-ae98fedb2371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignin']/div[5]/a</value>
      <webElementGuid>f33c227e-99d5-48a1-af9f-ab897e4acacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'现在创建一个。')]</value>
      <webElementGuid>2f725f32-77b1-44b3-89c4-3c7ee8d83692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='还没有StrongGate ID？'])[1]/following::a[1]</value>
      <webElementGuid>542fc9c4-b5e7-496c-a402-a1eb518f8f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登录'])[2]/following::a[1]</value>
      <webElementGuid>664cdc04-7b43-4063-8dfe-8cba8c6a10c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条款'])[1]/preceding::a[1]</value>
      <webElementGuid>3cdfcede-e61f-4b03-a684-bf03da86c34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='现在创建一个。']/parent::*</value>
      <webElementGuid>c5b01d88-92e3-4b82-a6c7-cb40b7c3ef22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/idp/stronggate/signup')]</value>
      <webElementGuid>73056f68-f47d-4d25-831d-7b302a25b02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>e63edd3b-7138-49d8-84ad-6f5d71e433cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/idp/stronggate/signup' and (text() = '现在创建一个。' or . = '现在创建一个。')]</value>
      <webElementGuid>3b80d1e6-76aa-40c2-8688-cb0f81f3ae0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
