<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__teamName</name>
   <tag></tag>
   <elementGuidId>1415934a-9b7c-4cbb-a603-57a4fa99926f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt-team-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt-team-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;您的团队名称或公司名称&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac4b6338-2095-4a14-92ac-d7a689561422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-team-name</value>
      <webElementGuid>15d5cb71-1210-483e-b9b9-c8e901df3936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teamName</value>
      <webElementGuid>824f2ab2-3330-4021-870c-6bd4d7f5c4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12af24ba-bd13-4df0-9473-3aa9c0ebc576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>verification()</value>
      <webElementGuid>0b742675-0a10-4152-a7b3-21d125173a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>teamNameBlur()</value>
      <webElementGuid>cae08197-6f1a-4897-bb28-d7650a3200f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>teamNameFocus()</value>
      <webElementGuid>8e17fd92-057a-4a07-80b6-452c9ef4d037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>您的团队名称或公司名称</value>
      <webElementGuid>1b087996-9fcc-4242-b803-37429cebbb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt-team-name&quot;)</value>
      <webElementGuid>532176fb-25f6-4eb3-873c-cf8edf44670c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt-team-name']</value>
      <webElementGuid>e507775c-44ac-4c29-a923-75483bd2a531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignUp']/div[4]/input</value>
      <webElementGuid>82e22fed-6d35-4a95-a155-4dd89f66afef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b2051804-a09b-48bc-8b0e-6a1f337a5285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txt-team-name' and @name = 'teamName' and @placeholder = '您的团队名称或公司名称']</value>
      <webElementGuid>17020b99-fc1f-4f6e-9594-38bee064aeaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
