<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_StrongGate</name>
   <tag></tag>
   <elementGuidId>15d98fa4-ddec-4b4b-b9e6-6defab7acd37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='onSignUp()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;创建一个新的StrongGate团队。&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ef540da-ca98-4612-9a7a-c969d64e7fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8d35ab77-9362-45bd-8b94-5e078cadc892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onSignUp()</value>
      <webElementGuid>0007db75-078f-4b9a-b523-0e6c82701333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>创建一个新的StrongGate团队。</value>
      <webElementGuid>7ae15862-3145-4d71-b326-578c728a0e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignIn&quot;)/div[@class=&quot;page-center ztn-page-t300&quot;]/a[1]</value>
      <webElementGuid>f1b82483-7729-415c-a7d8-2606705eebeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='onSignUp()']</value>
      <webElementGuid>38397cf8-11c9-4bcf-8d90-566ba6862d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignIn']/div[8]/a</value>
      <webElementGuid>fe6722fb-a3a0-43b0-8442-cc8a957bb234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'创建一个新的StrongGate团队。')]</value>
      <webElementGuid>d8bb29cb-8300-457a-9548-ea14187fa311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='创建新的StrongGate？'])[1]/following::a[1]</value>
      <webElementGuid>fdf949b0-f6b2-4907-bcf8-57e43e3861af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用您的电子邮件地址查找您的团队域。'])[1]/following::a[1]</value>
      <webElementGuid>4c43b3d0-0311-43ec-b3bb-016f571f4f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条款'])[1]/preceding::a[1]</value>
      <webElementGuid>98c5356c-f66c-4387-813b-d1e6afde5652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='创建一个新的StrongGate团队。']/parent::*</value>
      <webElementGuid>49958e1c-417e-4e27-a2c8-10d2b841ca27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>5d8ec6dd-1cc9-4f7d-a928-5f071bb7425b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>bb1d0193-7aed-4619-aa02-7f511cd60844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '创建一个新的StrongGate团队。' or . = '创建一个新的StrongGate团队。')]</value>
      <webElementGuid>f2322ac9-1d25-46e1-9aa6-dea65719f358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
