<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Secure Network</name>
   <tag></tag>
   <elementGuidId>7d3c9bdb-0d3f-46a0-a252-c45e44c89519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secure-confirm-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='secure-confirm-button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'secure-confirm-button' and (text() = 'Add Secure Network ' or . = 'Add Secure Network ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Secure Network&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e42c77f-99c5-4d9d-bf3f-4167aaf87a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dd2b0c6-90a7-459d-af06-cee74142daeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86c5adee-4502-44d8-9da8-d32653ea3967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secure-confirm-button</value>
      <webElementGuid>cb2bf4e5-5840-40e4-b860-fed8ccc944bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Secure Network </value>
      <webElementGuid>ca6a20f6-68fd-46b1-a0bb-1b941f8f7f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secure-confirm-button&quot;)</value>
      <webElementGuid>a8eb857d-f722-497a-9520-1e568c027f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='secure-confirm-button']</value>
      <webElementGuid>c61b8caa-1122-473f-844a-78cc4114c6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div[2]/div/div/div/form/div[6]/div/button[2]</value>
      <webElementGuid>e0bd1ce4-b625-4363-9b71-d4588865251f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>9e986f55-fe91-4008-9e35-60cca28d3b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Relay and Connector'])[1]/following::button[2]</value>
      <webElementGuid>ff3a992e-aa6d-4db5-ab1e-4d8a600f557a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/preceding::button[1]</value>
      <webElementGuid>feb5c2c6-eee7-48b4-a6d6-3dc2bc22ede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>58a2185c-f66f-4ae0-b959-c72223a7e526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'secure-confirm-button' and (text() = 'Add Secure Network ' or . = 'Add Secure Network ')]</value>
      <webElementGuid>615ce3b2-42ea-4152-911b-1186aa7a671b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
