<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Group</name>
   <tag></tag>
   <elementGuidId>785118a6-c5d1-4dea-9928-f25202621293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#groupDialog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='groupDialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Group&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c779b754-2740-4486-8d9c-1c18a3818a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9e4cd97-73c1-48a4-8608-8fd925e6c887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a1ee61a-5b23-4dca-9814-9b762dd7018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--small ztn-page-t200 button</value>
      <webElementGuid>53c5a6a6-b0b3-4826-88e2-a3c14da8e8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupDialog</value>
      <webElementGuid>53de6b15-d1ed-4df2-b33e-2804bb23728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Add Group </value>
      <webElementGuid>25ab64c3-6d6f-4fc2-bd60-9c52f1b0cfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupDialog&quot;)</value>
      <webElementGuid>9b22e857-a30c-4932-8a34-937ea3953ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='groupDialog']</value>
      <webElementGuid>73b1dae4-aae9-46f4-b3b9-1fdbb1a4ec77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-id-6974-14']/div/form/div[2]/div/button</value>
      <webElementGuid>d92b4311-b8e6-4f3d-a2b7-8b67eba94288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button</value>
      <webElementGuid>160fd4e2-3635-4948-922d-921eb1d9723d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'groupDialog' and (text() = '  Add Group ' or . = '  Add Group ')]</value>
      <webElementGuid>f31097bd-0d0d-41ed-89e3-73d0a30805de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
