<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__search-secure</name>
   <tag></tag>
   <elementGuidId>2f3bc03f-e21b-4de8-903a-2b3a39372988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-enable > #search-secure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-secure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2aea4b6-74bf-4281-b73b-f478ad439dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>425cbff1-0d3e-419b-80ff-f8f0cf60d786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-secure</value>
      <webElementGuid>df2033e0-1450-4547-8cc7-406ed038140d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>6307534f-1ccf-40eb-a8d8-ea4ab305b265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3&quot;]/div[@id=&quot;search-secure&quot;]/div[@class=&quot;search-box me-2&quot;]/div[@class=&quot;search-enable&quot;]/input[@id=&quot;search-secure&quot;]</value>
      <webElementGuid>451bd7f0-a4d2-4d27-ae18-14994ca6e094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-secure']</value>
      <webElementGuid>841589bf-b673-422d-aaa0-28bc7f981eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-secure']/div/div/input</value>
      <webElementGuid>54abe305-1fa4-44ff-8bef-108596ef4e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>8adf597c-a758-44c1-8d1a-700340394233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-secure' and @placeholder = 'Search...']</value>
      <webElementGuid>bd3935c8-02a7-4a94-822d-644371974ede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
