<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_confirm (1)</name>
   <tag></tag>
   <elementGuidId>8fd2e489-57c5-4733-9cf7-07f27a92ff9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resource-logo-confirm > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='connector-confirm-button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>181db315-bb5d-4f31-aa6e-4682c2df8089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>bf023b1b-e473-4ae5-a71c-aa6f8cbce20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resource-logo-confirm&quot;)/span[1]</value>
      <webElementGuid>8f594939-8168-44d3-817b-066d9d2df9e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='resource-logo-confirm']/span</value>
      <webElementGuid>610bb787-2979-4e6b-82e1-5523b24866b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Default logo'])[2]/following::span[2]</value>
      <webElementGuid>c4194fef-acff-4e46-b07e-12d753bb77e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added Policies for:'])[1]/preceding::span[1]</value>
      <webElementGuid>6c2336c2-46d3-42e5-97d0-19d8a2d3b6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[1]/preceding::span[1]</value>
      <webElementGuid>94f232e3-e6bc-4352-a434-a9dd7d83d1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='confirm']/parent::*</value>
      <webElementGuid>4635cc05-a4c4-428a-8824-c2ecf99f63c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>6511d219-e9fc-4201-87a6-a58853b06adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'confirm' or . = 'confirm')]</value>
      <webElementGuid>bd932eb2-232d-409f-933c-2b4e0e6956d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
