<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>2a970f9b-823c-4171-8ea3-ef9d5c5108bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resource-confirm-button > span.ztn-page-t400.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='resource-confirm-button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5ee7e65-7f89-4450-b1d1-7bb7959a4031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t400 text</value>
      <webElementGuid>caf6139e-8789-4f4f-a07f-8fa821fec718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save </value>
      <webElementGuid>829cf087-f133-4f56-8e6d-d4322193a265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resource-confirm-button&quot;)/span[@class=&quot;ztn-page-t400 text&quot;]</value>
      <webElementGuid>5194015d-80cf-459d-abf0-2cbe3cb0605e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='resource-confirm-button']/span</value>
      <webElementGuid>7b408cdb-7114-4d4e-a01d-963f30016ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::span[1]</value>
      <webElementGuid>8f5c5a1f-0b54-4051-91de-e3b495599a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Created Policy'])[1]/following::span[2]</value>
      <webElementGuid>0a9c5238-20dc-4635-90e2-78707af3d0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/preceding::span[2]</value>
      <webElementGuid>bff8527d-0b82-475e-a7be-e958f1e7f156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow'])[1]/preceding::span[2]</value>
      <webElementGuid>a6c1fdd2-0771-442c-8ad1-0f6c0f381bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>f303f45b-90fa-4a2a-9e69-1f7b0917df94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button[2]/span</value>
      <webElementGuid>a8fa1bf4-953c-451a-afd1-79d22f801f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save ' or . = 'Save ')]</value>
      <webElementGuid>646c351f-277e-46fe-9a9f-d4e7604d3c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
