<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add Resource (1)</name>
   <tag></tag>
   <elementGuidId>b5600481-fdad-4db9-bf0c-6fa13937bc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ztn-page-t400.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-resource']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;add-resource&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Resource&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b90ec092-4101-4c5a-bec4-c97917fc10fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t400 text</value>
      <webElementGuid>7970e7f8-6994-4392-8b96-7d5ca95912e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Resource </value>
      <webElementGuid>f0d2f754-19a7-4476-836c-d58b9d8a7da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-resource&quot;)</value>
      <webElementGuid>6b2ba648-76f7-40d5-bc35-dae34323334d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-resource']/span</value>
      <webElementGuid>1e2faa4e-32ac-4156-9c75-551216546abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::span[1]</value>
      <webElementGuid>f1302712-6867-4997-abcd-560a3ccf1a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resource Name'])[1]/preceding::span[1]</value>
      <webElementGuid>fb4dea77-524c-4ab0-a6f5-9193fafdfda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specification'])[1]/preceding::span[1]</value>
      <webElementGuid>1889a9f7-b484-48fa-81ec-13963a0da5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Resource']/parent::*</value>
      <webElementGuid>bf231f40-5dc9-4a12-8d29-3ca047834857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>b20b5db0-8778-4219-8869-7c829a1a4cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add Resource ' or . = 'Add Resource ')]</value>
      <webElementGuid>92e55d65-fa72-4f29-bf49-7b7ed94e6764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
