<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(Optional)_policy-desc-dialog</name>
   <tag></tag>
   <elementGuidId>647bbcda-9039-4ba9-ba5c-3dda4b392b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policy-desc-dialog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='policy-desc-dialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#policy-desc-dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>834aeb18-50f5-495b-9321-034824f450ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-textarea__inner</value>
      <webElementGuid>30c09360-de6e-4084-af1a-c78480ac90cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f89d7447-3307-408d-accf-09731f7f446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f17ad36-8b87-4220-9372-136e8fc95f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policy-desc-dialog</value>
      <webElementGuid>a97760aa-d609-4dfd-aab5-32309c89afd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-desc-dialog&quot;)</value>
      <webElementGuid>0b653bfe-7bfb-4bbf-8ff9-f6972e5b4e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='policy-desc-dialog']</value>
      <webElementGuid>6ff750d3-4421-48ba-80e6-93234bfbbdf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-id-6974-14']/div/form/div/div[4]/div/div/div/textarea</value>
      <webElementGuid>8b813a6a-8233-436c-8ad9-ca2815014887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/textarea</value>
      <webElementGuid>492dfa72-81cc-4bb8-8a13-747ed6a48dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'policy-desc-dialog']</value>
      <webElementGuid>84764dd3-a1fb-43cd-af07-fb68d99ddc6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
