<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_test136c9fatest.com</name>
   <tag></tag>
   <elementGuidId>a68ad394-e9e3-43ea-a886-34c53f805736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSignUp']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t2000.page-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;test136c9fa@test.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>efe20c10-bd41-4076-9402-7b83b3ebd008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-t2000 page-center</value>
      <webElementGuid>3aa76bf4-e2ac-4972-b3f4-59603804a59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test136c9fa@test.com</value>
      <webElementGuid>64c58cf2-f84d-4a85-9afc-07fc79551ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignUp&quot;)/div[@class=&quot;ztn-page-t2000 page-center&quot;]</value>
      <webElementGuid>1cee9315-87f8-4a0a-a5bc-983a7dbda6e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignUp']/div[2]</value>
      <webElementGuid>e08e3fb5-5fe2-4cc7-99cc-82f540218bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::div[1]</value>
      <webElementGuid>ac66cc32-bf9c-4be3-b276-511e8f9247e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='欢迎'])[1]/following::div[1]</value>
      <webElementGuid>a9a10f45-eaed-499b-bd0d-e3e6f9a4d171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='请告诉我们更多关于您自己的信息，以完成团队的组建。'])[1]/preceding::div[1]</value>
      <webElementGuid>a356f56b-6811-48f0-82c7-26d5f63419a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='团队名称：'])[1]/preceding::div[2]</value>
      <webElementGuid>3f3f19f3-658d-41f0-89b0-2f12e1047938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test136c9fa@test.com']/parent::*</value>
      <webElementGuid>45e7cc6b-24a8-4764-9983-b57e1bd66db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>0a586fb8-7b3b-418f-a02b-a602ba0e594f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'test136c9fa@test.com' or . = 'test136c9fa@test.com')]</value>
      <webElementGuid>799f385d-5ea3-4430-b935-090ac09fdb64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
