<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>95fcb684-5216-48b5-85b5-eeaeb7c51257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='active']/div/div[2]/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ztn-page-t200n.label-left > span:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;再次发送电子邮件&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c619d84-c65e-47b3-843b-044ae23e4752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>再次发送电子邮件</value>
      <webElementGuid>ec46c550-c82b-476a-a03a-e39beb6e38a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;active&quot;)/div[@class=&quot;div-border&quot;]/div[@class=&quot;page-center mb-auto&quot;]/div[@class=&quot;ztn-page-t200n label-left&quot;]/span[2]</value>
      <webElementGuid>39a22698-7625-4f07-b8d9-d602e4aaa0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='active']/div/div[2]/div[2]/span[2]</value>
      <webElementGuid>f1cb30e7-0cd5-430e-b74a-6f97fb61f5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='重新发送'])[1]/following::span[1]</value>
      <webElementGuid>ea49b6a0-152f-4d2a-8ed5-b1419e6ad48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='单击'])[1]/following::span[1]</value>
      <webElementGuid>28dee622-8006-43b6-b5ec-28bc327b6ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='在此处输入您的新密码：'])[1]/preceding::span[2]</value>
      <webElementGuid>1cdc917c-b0d9-4395-b211-3d74a72bdd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示'])[1]/preceding::span[2]</value>
      <webElementGuid>b59e6e49-96c1-4747-837b-ed5a7ac172f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='再次发送电子邮件']/parent::*</value>
      <webElementGuid>ae5c66a3-0946-403d-b282-c52545a18919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>ef8f2e27-643b-479e-a159-6bd857563516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '再次发送电子邮件' or . = '再次发送电子邮件')]</value>
      <webElementGuid>edd69d44-2bf9-4963-8cb9-781e348149f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
