<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_163</name>
   <tag></tag>
   <elementGuidId>51ac0629-09e3-47dd-b821-2f6312d0a08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.bdsug-overflow.c-line-clamp1.bdsug-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='normalSugSearchUl']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;163邮箱登录&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f037168d-79e1-4edc-a14c-30523d13df28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>163邮箱登录</value>
      <webElementGuid>c6513055-411d-46d8-9303-af818d4ce99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bdsug-overflow c-line-clamp1 bdsug-s</value>
      <webElementGuid>c292c132-6c66-425e-8efd-3f72b6e1e62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>163邮箱登录</value>
      <webElementGuid>cb0c5dcd-4d4d-41bf-82e2-71fa3e32a923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normalSugSearchUl&quot;)/li[@class=&quot;bdsug-overflow c-line-clamp1 bdsug-s&quot;]</value>
      <webElementGuid>c8437cec-ad6f-4ff2-a42c-1e143b02fc0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='normalSugSearchUl']/li</value>
      <webElementGuid>b497ab21-3e0b-4d31-9601-a4ce1d9939ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='请按“回车”键发起检索'])[1]/following::li[1]</value>
      <webElementGuid>fa967ba7-5627-44e9-85a3-fcc055f7a70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::li[1]</value>
      <webElementGuid>359b521d-a640-4fce-b302-09c313075687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='相册'])[1]/preceding::li[1]</value>
      <webElementGuid>0eb0312b-98ad-450b-9980-56e8768a072a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='163']/parent::*</value>
      <webElementGuid>cf2c8efd-09f3-41a6-a7a4-325995010ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>53e42681-5fa4-460c-9659-a9149901053f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '163邮箱登录' or . = '163邮箱登录')]</value>
      <webElementGuid>7c546c4f-94d4-45f7-a5e3-1abd71c69b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
