<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AND  . . .  OR</name>
   <tag></tag>
   <elementGuidId>1aad41ca-b478-4aae-8dc7-798f4fc080e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inclusive > div:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inclusive']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inclusive div >> internal:has-text=&quot;AND . . . OR . . .&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ddcbb10-1bad-4bf7-b15f-f84b92fea211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AND  . . .   OR  . . . </value>
      <webElementGuid>0f35cd2d-2e89-4b65-bfdc-92ecf558c803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inclusive&quot;)/div[4]</value>
      <webElementGuid>c03f8a81-bb76-4a75-b8fa-c942b61e43bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inclusive']/div[4]</value>
      <webElementGuid>23641d1b-341c-4aeb-887f-9dfbf0559538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(inclusive)'])[1]/following::div[1]</value>
      <webElementGuid>9f6a089c-bca0-4dd6-babf-f9f3ac0b07fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANY'])[1]/following::div[1]</value>
      <webElementGuid>4e00b559-fb2c-4d92-b4c7-be454c5b7090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]</value>
      <webElementGuid>28067d25-f4de-459b-93c3-f0c422b57991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  AND  . . .   OR  . . . ' or . = '  AND  . . .   OR  . . . ')]</value>
      <webElementGuid>b7e56a22-90f1-4ada-adfe-79ae26674044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
