<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AND if  NONE of these are true (exclusion) OR</name>
   <tag></tag>
   <elementGuidId>8b4bdc19-3bb3-4e5b-9804-a97667cf45bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exclusion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='exclusion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AND if NONE of these are true (exclusion) OR . . .&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30fc6049-768e-4273-9501-23cac550bf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exclusion</value>
      <webElementGuid>b162154b-470a-4161-8018-869e280cbf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>eacb4b8a-cf38-4a4a-9b3b-40211c517597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AND if   NONE  of these are true  (exclusion)  OR  . . . </value>
      <webElementGuid>bc5491e0-6902-47f5-a6d2-0ca46fec456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exclusion&quot;)</value>
      <webElementGuid>1d8fc420-4d32-491e-b2a3-3a2c941f3131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='exclusion']</value>
      <webElementGuid>26fc2b25-ad32-430d-8031-7a60dacf3315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/form/div[3]/div/div/div/div[2]/div[2]/div[4]</value>
      <webElementGuid>dad882e4-5f8e-49e8-a590-7b30ec0a0cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. . .'])[3]/following::div[2]</value>
      <webElementGuid>59242bb8-881c-46cb-9d74-038c9e1623f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]</value>
      <webElementGuid>fd02316f-e601-47bb-aa92-7e9ea5142495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'exclusion' and (text() = 'AND if   NONE  of these are true  (exclusion)  OR  . . . ' or . = 'AND if   NONE  of these are true  (exclusion)  OR  . . . ')]</value>
      <webElementGuid>9d8bc244-17cb-41e4-9fc6-982d79552f6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
