<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_By these members</name>
   <tag></tag>
   <elementGuidId>09314eef-0ba7-4a8f-b38e-8579bc08d656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'By these members: ' or . = 'By these members: ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='checkBox_lab'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;By these members:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03d6bf86-208c-4900-bad8-734f7d2d8788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ztn-page-h300 check-font</value>
      <webElementGuid>04d6f85d-efcc-4f35-8279-bf81d61138cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By these members: </value>
      <webElementGuid>df65bc61-a132-4197-bcd9-a78053bdf44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/form[@class=&quot;el-form el-form--default el-form--label-top&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row col-12&quot;]/div[@class=&quot;el-form-item is-no-asterisk asterisk-left el-form-item--feedback&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;ztn-page-t400 col-md-8 approval&quot;]/div[1]/div[3]/div[@class=&quot;mb-1&quot;]/label[@class=&quot;el-checkbox is-checked&quot;]/span[@class=&quot;el-checkbox__label&quot;]/div[@id=&quot;checkBox_lab&quot;]</value>
      <webElementGuid>c8dc3e1d-a55e-4098-ad1d-1a4a5232e783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBox_lab</value>
      <webElementGuid>a00a76d9-b021-4329-8805-f9eb5b084b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='checkBox_lab'])[3]</value>
      <webElementGuid>dceec661-3437-4ef6-aebb-5522dbe8d075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/form/div/div/div[6]/div/div/div[2]/div/div[3]/div[3]/label/span[2]/div</value>
      <webElementGuid>aec7ace4-79e9-48b2-950a-2a3172811fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By the matched group administrators in the following group list'])[1]/following::div[2]</value>
      <webElementGuid>7c9135ca-41c1-4036-bdb9-e5c8aab1608d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By team administrator'])[1]/following::div[4]</value>
      <webElementGuid>86da542f-4c9a-4a5e-aa69-8e0e52f64a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='By these members:']/parent::*</value>
      <webElementGuid>bf3c5303-728b-4607-819b-2a5083e018f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span[2]/div</value>
      <webElementGuid>8519600e-9ff5-4bc1-ad9a-bd889d5b4e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkBox_lab' and (text() = 'By these members: ' or . = 'By these members: ')]</value>
      <webElementGuid>1603956c-37a3-4bb2-a34a-6900f4abe7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'By these members: ' or . = 'By these members: ')]</value>
      <webElementGuid>567816e2-0e98-4447-8ec4-2458b3c29465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
