<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OR_el-range-input</name>
   <tag></tag>
   <elementGuidId>8cde507b-7810-4ac4-ba0f-7466fd754c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.el-range-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Start Time&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5bc58e9-7b92-4eb6-bebf-2a27a3dcc9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b64b641f-e681-4a83-ac56-a99cebe06612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start Time</value>
      <webElementGuid>d048edce-fcb9-48e0-8af8-5c045d79b2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-range-input</value>
      <webElementGuid>12fe7063-9701-4057-87f8-657d821d7c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exclusion&quot;)/div[4]/div[@class=&quot;tree-data&quot;]/table[@class=&quot;rule&quot;]/tbody[1]/tr[1]/td[@class=&quot;operator-td&quot;]/div[1]/div[@class=&quot;el-date-editor el-date-editor--timerange el-input__wrapper is-active el-range-editor el-range-editor--large ztn-time-picker el-tooltip__trigger el-tooltip__trigger&quot;]/input[@class=&quot;el-range-input&quot;]</value>
      <webElementGuid>fcd385e5-6594-4b0e-a7c1-28e5a37c8ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[15]</value>
      <webElementGuid>4d016ac4-90a3-4a69-8e08-1c36a572fbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exclusion']/div[4]/div[3]/table[2]/tbody/tr/td[3]/div/div/input</value>
      <webElementGuid>c60236d5-fd96-4793-a37f-d253236fc03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/input</value>
      <webElementGuid>1c93400d-34be-4ae4-8ea6-9fbefa0f68ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Start Time']</value>
      <webElementGuid>6685d70e-7821-4d26-9702-4aec57d876bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
