<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Botswana</name>
   <tag></tag>
   <elementGuidId>843e6402-45b7-432b-af8d-41856711a7d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-7614-393</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='el-id-7614-393']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Botswana&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5ada609a-9a3c-4e92-bee0-85bc277fe6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-id-7614-393</value>
      <webElementGuid>a6c1a938-838f-439e-a429-8768ef70b7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item hover font-size-11</value>
      <webElementGuid>bf6eb421-ac29-4a70-8bef-95d82a6ac25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>974a6682-887c-4890-9d2b-d152d43bd729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fe12f4bb-041e-49e1-a4b7-d02e7d5d0681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Botswana</value>
      <webElementGuid>a099e67a-7852-4b73-8d4c-58fb0edc9a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-7614-393&quot;)</value>
      <webElementGuid>7c581458-c2e8-4814-bce0-c4d30b24c343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='el-id-7614-393']</value>
      <webElementGuid>ff85916a-c338-47ec-9603-cce919114239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='el-id-7614-389']/ul/li[2]/ul/li[4]</value>
      <webElementGuid>e1331035-7cbf-4140-bd7d-b78b10b6ff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benin'])[1]/following::li[1]</value>
      <webElementGuid>a909556b-14cc-4c68-9b97-a487bc2322d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angola'])[1]/following::li[2]</value>
      <webElementGuid>24085ba7-163a-4200-9d2a-706be84b6b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BurkinaFaso'])[1]/preceding::li[1]</value>
      <webElementGuid>9114914d-a31f-48e7-a11b-9c45a9011f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/ul/li[2]/ul/li[4]</value>
      <webElementGuid>3ed8bc0b-bc16-47c8-b43d-2e9b0df4bdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'el-id-7614-393' and (text() = 'Botswana' or . = 'Botswana')]</value>
      <webElementGuid>c740df4a-e7f1-4593-9bb6-dda24b44e45c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
