<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_In</name>
   <tag></tag>
   <elementGuidId>2e0a8a23-e5f0-43f3-bbb7-75f4197a40e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-7614-101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='el-id-7614-101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;In&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>aa4b0ab2-389a-478a-9a28-77183602e4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-id-7614-101</value>
      <webElementGuid>9d3fbf91-5ef9-4a0a-bf1f-cd8823eb2167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item hover font-size-11</value>
      <webElementGuid>edd7f0af-113b-4078-ab23-ff8f1d629fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>00b01a89-81df-4b85-b63a-0262844048b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b5464b5-52ba-48a7-b3d3-70447b3b1430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In</value>
      <webElementGuid>4da9dc85-c2db-4f7e-b42f-99918242c05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-7614-101&quot;)</value>
      <webElementGuid>1b4d24d3-2857-40de-8764-2bee0cd77d7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='el-id-7614-101']</value>
      <webElementGuid>57237982-2f17-4174-93ed-4a1a4aab1a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='el-id-7614-97']/li</value>
      <webElementGuid>499d0d89-a438-4466-8b1a-ab1d73279c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disk Encryption'])[1]/following::li[1]</value>
      <webElementGuid>9c11b25c-e33d-49e3-a85a-ccd017f2fe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domain User'])[1]/following::li[2]</value>
      <webElementGuid>a32cc6e9-162c-4f3b-b835-3a071174fc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NotIn'])[1]/preceding::li[1]</value>
      <webElementGuid>90a8d715-7c60-44dc-a578-e81836c4f123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ul/li</value>
      <webElementGuid>edccd50c-602c-4cb4-9eb0-d7292f0d4e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'el-id-7614-101' and (text() = 'In' or . = 'In')]</value>
      <webElementGuid>3c760a99-1093-4f09-a2dc-665d6ffd3a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
