<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Allow</name>
   <tag></tag>
   <elementGuidId>4a8c6e9e-88b9-4257-8db5-93beb87a5dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='radio']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.el-radio-button__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Allow&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2259af96-101c-4d46-9de5-7f8fcbb4a2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-radio-button__inner</value>
      <webElementGuid>9e20b538-6e0b-43b1-bdeb-13b3ebc7374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow </value>
      <webElementGuid>3564775b-21c0-4572-baec-4ab8afada93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-7261-147&quot;)/label[@id=&quot;radio&quot;]/span[@class=&quot;el-radio-button__inner&quot;]</value>
      <webElementGuid>d1f03eb8-25b3-400a-b385-702782c1c665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='radio']/span</value>
      <webElementGuid>ff90a816-7ef7-4f2c-a429-db39ae298fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow']/parent::*</value>
      <webElementGuid>60871243-7c75-4aeb-8b85-13bfc1d7a0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/span</value>
      <webElementGuid>d3a95c46-8d61-4305-b5b6-b6d8547f9bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Allow ' or . = 'Allow ')]</value>
      <webElementGuid>bb68eb1a-639b-4315-b977-f0a0da3343a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
