<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test666test.com</name>
   <tag></tag>
   <elementGuidId>774b403d-321f-43d9-8f7f-417571df76e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-7614-69 > span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'test666@test.com' or . = 'test666@test.com')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='el-id-7614-69']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;test666@test.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9fb590ee-f755-4dfa-98c1-e02c9664b783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test666@test.com</value>
      <webElementGuid>025d200e-6fa0-436f-8029-e79941b759b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-7614-69&quot;)/span[1]</value>
      <webElementGuid>2081a73e-221b-4dd9-81f7-0b98c837ee11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='el-id-7614-69']/span</value>
      <webElementGuid>6eabb04e-09a0-4691-b1f8-82408fcec4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test@test.com'])[1]/following::span[1]</value>
      <webElementGuid>7ba0587d-78e9-40fc-959d-46d1dba5150b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testeca56a@test.com'])[1]/following::span[2]</value>
      <webElementGuid>5216e40c-0241-4102-9387-fc876a42d8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test20114c@test.com'])[1]/preceding::span[1]</value>
      <webElementGuid>160a4bcc-2aa1-47c2-a327-9f29d5e3b799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test333@test.com'])[1]/preceding::span[2]</value>
      <webElementGuid>a493e94f-a0e4-4f7c-a11e-efb0fd2a9f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test666@test.com']/parent::*</value>
      <webElementGuid>3d513490-207a-4300-a08d-c00a6a654148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span</value>
      <webElementGuid>3e087394-cfd8-4ba9-a5cb-80c5bdd2951c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'test666@test.com' or . = 'test666@test.com')]</value>
      <webElementGuid>c6ef2b12-2f0d-4ad6-b2d9-497a418fa2cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
