<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test333test.com</name>
   <tag></tag>
   <elementGuidId>ef69f1e2-1e2d-45fb-828a-ef0431d6b48b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-7614-71 > span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'test333@test.com' or . = 'test333@test.com')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='el-id-7614-71']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;test333@test.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82a4ac48-2c31-4b67-bae9-7bdd86955b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test333@test.com</value>
      <webElementGuid>ef1db30f-73df-408f-a012-5b88fc30f07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-7614-71&quot;)/span[1]</value>
      <webElementGuid>8638324d-46f2-42c0-ada6-31603f34ae29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='el-id-7614-71']/span</value>
      <webElementGuid>70d67917-7145-4ebb-bfc7-60227fb9646c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test20114c@test.com'])[1]/following::span[1]</value>
      <webElementGuid>43871fcb-cbf3-4268-b3f8-e6ab283c7b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test666@test.com'])[2]/following::span[2]</value>
      <webElementGuid>5b02811b-62f4-4087-b93a-74f196cfdf8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test333@test.com']/parent::*</value>
      <webElementGuid>9bda0a6e-d2c9-48ff-976c-d0d8a66715c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/span</value>
      <webElementGuid>7c84f900-7cbe-4921-a0d4-769bcbd101bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'test333@test.com' or . = 'test333@test.com')]</value>
      <webElementGuid>8310452f-7cd2-4ce2-81bc-30f03aed4697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
