<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description(optional)_policyDesc</name>
   <tag></tag>
   <elementGuidId>ced7f167-0dd5-4f18-8141-f68097b330ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policyDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='policyDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#policyDesc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>50f64693-20e2-4a1f-ac37-6d07705fd0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-textarea__inner</value>
      <webElementGuid>eb5c4aaf-9ee6-46cf-a00d-5cc1c6f42b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20e7cc91-0e13-4e3b-b803-fa4b6178c1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c86c81c1-acf2-4116-86de-32aa57f07641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policyDesc</value>
      <webElementGuid>a0a472e6-39ba-4c6f-801b-66ac1bcf46ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policyDesc&quot;)</value>
      <webElementGuid>7bf6403f-824c-4567-95ee-1b37840713cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='policyDesc']</value>
      <webElementGuid>d3d0d967-e726-49a5-a239-eb60a470cd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/form/div/div/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>c3aef300-dc76-45b5-8a4e-8cba1fc482ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f39ab387-ac6f-405d-83c7-b95bf34ed0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'policyDesc']</value>
      <webElementGuid>1c6ccc4b-b834-451d-a1bc-3b616b02bdb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
